### ISSUE TITLE
The name org.freedesktop.Notifications was not provided by any .service files

### ISSUE THREAD

**Issue by RidaAyed** [gnome-pomodoro/gnome-pomodoro#344]
Hi

Since upgrading Arch Linux from `4.15` to `4.16` via `$pacman -Syyu` I got this message upon running `$ gnome-pomodoro`:

```
** (gnome-pomodoro:4862): CRITICAL **: file notifications-capability.c: line 1118: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (g-dbus-error-quark, 2)
Segmentation fault (core dumped)
```
Any ideas where I should start digging?

**Comment by kafendt** [comment]
I am having the same issue

**Comment by chikh** [comment]
@RidaAyed It depends on your DE (or absence of it), but this have helped me: https://wiki.archlinux.org/index.php/Desktop_notifications#Standalone

**Comment by westofer** [comment]
this might help someone 

```bash
mkdir -p $XDG_DATA_HOME/dbus-1/services

echo '
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon-1.0/notification-daemon
' > $XDG_DATA_HOME/dbus-1/services/org.freedesktop.Notifications.service

```

**Comment by Lebsasha** [comment]
Thank you. It helped me with Linux Debian 10 with LXDE desktop environment. Although in my case, I need to replace the path to notification-daemon:<br> [D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon/notification-daemon

**Comment by DeepakDenre** [comment]
I am also getting the same error 


GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

In termux after installing tigervnc and xfce4 can anyone help

**Comment by slyfox1186** [comment]
For anyone concerned this fixed my issue.

[GitHub Script](https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/SlyFox1186%20Scripts/fix-dbus.sh)

**Comment by xbello** [comment]
> Thank you. It helped me with Linux Debian 10 with LXDE desktop environment. Although in my case, I need to replace the path to notification-daemon: [D-BUS Service] Name=org.freedesktop.Notifications Exec=/usr/lib/notification-daemon/notification-daemon

You must find where your `notification-daemon` lives, maybe using `locate notification-daemon`. In my Fedora + LXDE, it is at `/usr/libexec/notification-daemon`.

**Comment by dhjw** [comment]
On my minimal LXDE I also had to `sudo apt install notification-daemon`

**Comment by kamilprusko** [comment]
Changed the use of `org.freedesktop.Notifications` to be optional. Without it, notifications won't have buttons... I don't remember why we disable them. I assume it was a done for Unity.

XFCE supports buttons ok. It doesn't respect withdrawal of notifications. Notifications tend to accumulate on the desktop.

I haven't tested Pomodoro on a minimal LXDE. If buttons work ok, we could just just assume that buttons work on every desktop now.
