### ISSUE TITLE
Meson port

### ISSUE THREAD

**Issue by Cogitri** [gnome-pomodoro/gnome-pomodoro#351]
Hello,

I'd be interested in porting gnome-pomodoro to meson, however, I'd like to ask if you (upstream) are interested in adopting it first :)

**Comment by kamilprusko** [comment]
Hi,

Sure :) I think all official GNOME projects moved to meson by now. Makes no sense to stay behind.

**Comment by Cogitri** [comment]
> I think all official GNOME projects moved to meson by now. 

Well, not all, but most are, I'm working on a few others. I'll open a PR for this soon, thanks for the answer :)
