### ISSUE TITLE
Timer freezes on Wayland session on Fedora 30, Gnome 3.32

### ISSUE THREAD

**Issue by barrel0luck** [gnome-pomodoro/gnome-pomodoro#436]
I'm not sure if this is a duplicate of #380 
Timer freezes immediately after the start button is clicked on the Wayland session.
Edit: 
1. Pomodoro version 1:0.15.1-2.fc30
2. On Xorg session pomodoro doesn't even start. On running from terminal I get:
`Failed to register: Timeout was reached`

**Comment by aadilayub** [comment]
I'm also experiencing this issue

**Comment by c-orl** [comment]
I'm also experiencing this issue.

**Comment by alexmachina** [comment]
on Fedora 31, GNOME, Wayland session, is also freezing.

Switching to Xorg, the app works perfectly

**Comment by aadilayub** [comment]
I don't know what changed, but I no longer experience this issue on Fedora 31. Using the default GNOME Wayland session.

**Comment by barrel0luck** [comment]
Sorry, I'm still facing the issue. I'm on Fedora 31 as well. Using the
default GNOME Wayland session. All extensions disabled.

**Comment by tlnagy** [comment]
Can confirm this on Gnome 3.36 on Fedora 32 (using Wayland). Program freezes a couple seconds after start and then gnome offers to kill it.

**Comment by Chronomly** [comment]
Can confirm this on GNOME 3.36 on Fedora 32 on X session. Program starts fine and the timer starts then freezes then GNOME offers to kill it.
