### ISSUE TITLE
"Failed to enable extension error" Antergos 

### ISSUE THREAD

**Issue by talueses** [gnome-pomodoro/gnome-pomodoro#446]
Starting OS (manjaro) Pomodoro Version: "0.13.4" prompt a error: 
```
"Failed to enable extension error" 
TypeError: ExtensionSystem.logExtensionError is not a function.
```
Linux version: 5.3.1-arch1-1-ARCH

**Comment by kamilprusko** [comment]
I won't be much of help with Manjaro or Arch :(

Try removing your existing package and installing package `gnome-shell-pomodoro` from [AUR](https://aur.archlinux.org/packages/gnome-shell-pomodoro/) or from [source](https://gnomepomodoro.org). Instructions on installing from source are in the Download section.

**Comment by talueses** [comment]
It's a new fresh install. But I've install again and show me the same error.
