### ISSUE TITLE
Graphical glitches in Gnome 3.36

### ISSUE THREAD

**Issue by jpfender** [gnome-pomodoro/gnome-pomodoro#471]
I'm experiencing some minor graphical glitches which as far as I can tell don't impact functionality.

On mouseover, the extension icon expands to about 1.5 its size. Here's a comparison.

Normal:
![Normal](https://user-images.githubusercontent.com/685798/78623425-b9e22d00-78db-11ea-8936-b24984c3826b.png)
On mouseover:
![On mouseover](https://user-images.githubusercontent.com/685798/78623454-ca92a300-78db-11ea-95c1-3738621a91b3.png)

Furthermore, the start/pause/stop buttons in the popup menu are replaced by glitched glyphs:

![Popup glyphs](https://user-images.githubusercontent.com/685798/78623500-e26a2700-78db-11ea-89c8-862cf37398f4.png)

I also previously experienced an issue that caused the inflated-size icon to persist indefinitely, but I haven't been able to reproduce this.

I'm on Arch Linux, using the AUR package `gnome-shell-pomodoro 0.17.0-1` with gnome-shell 3.36.1-1.

As I said, functionality is not impacted at all, it just looks a bit weird.

**Comment by kamilprusko** [comment]
Thanks @jpfender  for reporting the issue.

Looks to me as if extension stylesheet didn't load... Is timer on the break screen in larger font size?

Do you use other extensions?

**Comment by jpfender** [comment]
I disabled the break screen when I first installed the extension (and couldn't find the option to re-enable it in preferences?), so I can't tell you that, sorry.

This is the only shell extension I've enabled.

**Comment by batisteo** [comment]
![Screenshot from 2020-04-08 13-41-06](https://user-images.githubusercontent.com/2727048/78780573-1fe3b880-799f-11ea-96f9-650e7ceff4c0.png)
For me it doesn’t get bigger on mouseover, just always.  
I’m on Fedora 32 beta, Gnome 3.36

**Comment by gw0** [comment]
I had no issues in Ubuntu 19.10 on Wayland, but they appeared in Ubuntu 20.04 using Gnome 3.36.1 on Wayland.

**Comment by dmnks** [comment]
Same issue on Fedora 32 GA (w/o any other 3rd party extensions); the circle as well as the pause/stop buttons in the dropdown menu get bigger, and the overlay text that shows up during a pomodoro break becomes too small.

**Comment by gsurkov** [comment]
I can confirm the issue, it happens exactly after returning from the blank screen (I have no screensaver or automatic lock set up)
Gnome 3.36.2 on Xorg, Arch Linux. Plugin built today from latest git.

**Comment by dmnks** [comment]
@gsurkov Thanks for the confirmation; one quick workaround I've found is to restart the current gnome session (ALT+F2, then type "r" and hit ENTER), but for that you need to be running on Xorg as Wayland doesn't support this yet.

**Comment by gsurkov** [comment]
@dmnks It works, but I decided to disable the blank screen altogether, will see if that fixes it.

**Comment by jpfender** [comment]
To hopefully narrow it down further: This only seems to happen upon locking/unlocking _if the timer is currently active_; at least, I haven't been able to reproduce it with an inactive timer.

**Comment by szpak** [comment]
Merging back #510 I would like to add that locking causes also very small timer font during the break:
![image](https://user-images.githubusercontent.com/148013/92252398-77467000-eece-11ea-9f74-52d60e5cc3c5.png)

Tested with gnome-shell-extension-pomodoro-0.17.0-1.fc32.x86_64 and Gnome Shell 3.36.5.

@jpfender Could you add to the title "... in Gnome 3.36"? It would be easier to find for people having problem with that version.

**Comment by Tommekk** [comment]
I have the same issue when I resume the pc from standby or when I have firefox with youtube in full screen mode and both times a pomodoro is running. I think it happens if a state change happens during this intervalls, but the gnome-shell is not reachable(?)

I have Manjaro 20.1 with GNOME 3.36.6 and installed gnome-shell-pomodoro 0.17.0-1 via pamac.

**Comment by JosseVanDelm** [comment]
I had the same issue on Arch, but I recently upgraded to gnome 3.38.1 and gnome-shell 1.18.1 and this seems to have solved the issue for me.

**Comment by jpfender** [comment]
Can confirm, upgraded to Gnome 3.38.1 and can no longer reproduce the issue.
