### ISSUE TITLE
./autogen.sh command fails with `./configure: line 2442` errors

### ISSUE THREAD

**Issue by penyuan** [gnome-pomodoro/gnome-pomodoro#492]
Hello,

I am trying to set up `gnome-pomodoro` in RHEL 8.2 with Gnome 3.32.2. I followed the instructions on the main website and want to install it into my home folder (instead of `/usr`) so I tried this command in the locally cloned git directory:

```
./autogen.sh --prefix=/home/[myuser]/.local/ --datadir=/home/[myuser]/.local/share
```

**Note:** I tend to install self-compiled programs into ~/.local/bin, that's why I use ~/local/ as the prefix. Is that correct?

However, this step fails with the following errors on the last lines:

```
[previous lines don't seem to have errors]
.....
configure.ac:14: installing './missing'
lib/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
./configure: line 2442: syntax error near unexpected token `git-directory'
./configure: line 2442: `AX_IS_RELEASE(git-directory)'
```

Am I missing something here? Can someone please advise on how to install `gnome-pomodoro` into a user's home directory? Thanks!

**Comment by levimake** [comment]
I'm also getting the same error.
```
./configure: line 2460: syntax error near unexpected token `git-directory'
./configure: line 2460: `AX_IS_RELEASE(git-directory)'
```

**Comment by levimake** [comment]
Fixed it.
Please make sure you've installed all libraries listed in this command.
`sudo apt-get install autoconf-archive gettext valac pkg-config desktop-file-utils appstream-util libappstream-glib-dev libglib2.0-dev gsettings-desktop-schemas-dev gobject-introspection libgirepository1.0-dev libsqlite3-dev libgom-1.0-dev libgstreamer1.0-dev libgtk-3-dev libcanberra-dev libpeas-dev libappindicator3-dev`

**Comment by penyuan** [comment]
Thanks @levimake. However, like I said in my original post, I am running RHEL 8.2, so the package names are different and it doesn' tuse `apt-get`, it uses `dnf`. For example, there is no `valac` package in the RHEL built-in or EPEL repositories.

And if the built app is unresponsive, I suspect there is another problem at play here?

**Comment by David-Else** [comment]
@penyuan I can't even get it to build on Centos 8.2 without it missing things. There is another support thread about this, could you comment on https://github.com/codito/gnome-pomodoro/issues/456  and say exactly which dependencies you have installed? Are you using the 3.32 branch? Cheers!

**Comment by Manamama** [comment]
I am on 
DISTRIB_DESCRIPTION="Zorin OS 15.3"
gnome-tweaks  --version 3.28.1

I had tried:
sudo apt-get install gnome-shell-pomodoro
but I got:
The following packages have unmet dependencies. gnome-shell-pomodoro : Depends: gnome-shell (>= 3.15) but it is not going to be installed
so I tried to build it from scratch. 
Got the same error. 
Levimake's fix above did help it compile but then I am stuck with an inoperative Pomodoro in the Tweaks/Extensions menu. 

Hm. 
Not sure how to remove it now :).

**Comment by Manamama** [comment]
OK, aptitude install suggested a fix:

    Install the following packages:                                            
1)     gir1.2-mutter-2 [3.28.4+git20200505-0ubuntu18.04.2 (bionic-updates)]     
2)     gnome-user-guide [3.28.2+git20180715-0ubuntu0.1+zorin1 (bionic)]         
3)     libmutter-2-0 [3.28.4+git20200505-0ubuntu18.04.2 (bionic-updates)]       
4)     ubuntu-wallpapers [18.04.1-0ubuntu1 (bionic)]                            
5)     ubuntu-wallpapers-bionic [18.04.1-0ubuntu1 (bionic)]                     

     Downgrade the following packages:                                          
6)     gjs [1.54.3-1build1+zorin1 (bionic, now) -> 1.52.5-0ubuntu18.04.1 (bionic
7)     gnome-shell [3.30.2-2ubuntu2+zorin4 (bionic, now) -> 3.28.3+git20190124-0
8)     gnome-shell-common [3.30.2-2ubuntu2+zorin4 (bionic, now) -> 3.28.3+git201
9)     gnome-shell-extensions [3.30.1-1+zorin1 (bionic, now) -> 3.28.0-2 (bionic

No, thank you. Just FYI.

**Comment by csasalu** [comment]
The change in prefix is not the issue @penyuan . I get the same error while installing on RHEL-8.
`gnome-pomodoro]$ ./autogen.sh --prefix=/usr --datadir=/usr/share
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --warnings=no-portability 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --force --warnings=no-portability
autoreconf: running: automake --add-missing --copy --force-missing --warnings=no-portability
configure.ac:19: installing './compile'
configure.ac:14: installing './missing'
lib/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: loading site script /usr/share/config.site
./configure: line 2442: syntax error near unexpected token `git-directory'
./configure: line 2442: `AX_IS_RELEASE(git-directory)'
`

**Comment by David-Else** [comment]
I don't think this is ever going to be fixed :( I am using https://flathub.org/apps/details/org.gnome.Solanum . It is not as advanced, but is minimal, written in Rust, and well maintained.

**Comment by penyuan** [comment]
> I don't think this is ever going to be fixed :( I am now using https://flathub.org/apps/details/org.gnome.Solanum . It is not as advanced, but is minimal, written in Rust, and well maintained.

Thank you for the suggestion @David-Else! I'll give it a try, then.

**Comment by emirhg** [comment]
> Fixed it. Please make sure you've installed all libraries listed in this command. `sudo apt-get install autoconf-archive gettext valac pkg-config desktop-file-utils appstream-util libappstream-glib-dev libglib2.0-dev gsettings-desktop-schemas-dev gobject-introspection libgirepository1.0-dev libsqlite3-dev libgom-1.0-dev libgstreamer1.0-dev libgtk-3-dev libcanberra-dev libpeas-dev libappindicator3-dev` . But the app built is unresponsive on my Ubuntu 20.04 Gnome

This worked for me on Ubuntu 21.04 after reinstalling Gnome the error showed up (it was working nicely before). It's definitely a dependency error, but not sure which package did the trick.

**Comment by kamilprusko** [comment]
Closing, as the project is using meson now.
