### ISSUE TITLE
Timer tab as default

### ISSUE THREAD

**Issue by ghost** [gnome-pomodoro/gnome-pomodoro#494]
When I open Pomodoro from my taskbar or tray icon it opens the app but in the "Stats" tab. I want to open it with the "Timer" tab as default. Is this possible?
By the way, I'm on Ubuntu 20.04 and Pomodoro's version is 0.16.0.

**Comment by AndreiMiculita** [comment]
Will unfortunately have to uninstall it. This is a fundamental issue with the program that makes it unsuitable as a daily driver.
