### ISSUE TITLE
Random switching between monitors during a break

### ISSUE THREAD

**Issue by tartansandal** [gnome-pomodoro/gnome-pomodoro#542]
On Fedora 33, when a break starts, I get random switching between my laptop and my monitor.
The delay between switches varies from less than a second to more than 5 seconds.
May be a Wayland issue. May be related to #356

**Comment by kamilprusko** [comment]
Is there anything relevant in gnome-logs? Filter by "gnome-shell"

**Comment by tartansandal** [comment]
Ah good point @kamilprusko :smile: 

The only thing showing in the logs when I trigger a break is "Timelines with detached actors are not supported".

Note, if I have something dynamic like Toggle Track running in a browser window, the switching is much faster.

**Comment by tartansandal** [comment]
@kamilprusko I made a short [screen cast](https://drive.google.com/file/d/1MzA5_rb1UmJ7tnPlHJ3h9thIkzqFtNJN/view?usp=sharing) of the behaviour which may clarify.

I'm running version 0.18.0 from the Fedora repositories, but if you want to make a branch with some extra instrumentation, I'm happy to run that locally.

**Comment by kamilprusko** [comment]
@tartansandal Thanks! Screen cast is very helpful :pray:

**Comment by tartansandal** [comment]
@kamilprusko It looks like some timer or event is being triggered and grabbing the screen focus.

**Is another app causing this?**

If I shutdown all my desktop apps, the rate of switching drops off to once every 8-15 seconds. 

If I run `htop` in a single `gnome-terminal` (which refreshes once per second) switching rate increases to once every 1-4 seconds (sometimes twice in a second). 

This suggests some interaction is at least affecting, if not causing, the problem.

**What about display settings?**

Here's a snapshot of my display setup which is not very clear from the screen cast:

![image](https://user-images.githubusercontent.com/3327775/105260040-287d4680-5be1-11eb-8e89-cc18399da024.png)

- Two screens: a laptop and an external monitor
- Both are hires screens (3800x2160 capable), but the laptop screen (OLED) is set to 2800x1620 (since physically smaller)
- Both screens are set to scale at 200%
- External monitor is set as primary
- Laptop screen is offset slightly so mouse moves cleanly between the two screens

I've tested after setting the screens to the same resolution, moving the screens to align at the edges, and setting the laptop as primary (in case we are hitting a weird wayland/mutter/clutter glitch) but still get the annoying switching. I think we can rule that out.

**What happens to the mouse?**

Mouse does not move. It stays on the screen where the break was triggered.

**What about "dim on idle", "screensaver", "show notifications on lock screen", "animations", ...**

Tried toggling these in turn, but still have the issue.

**What about other shell extensions?**

Turning off all extensions except `gnome-pomodoro` had no effect.

**What about background and autostart processes?**

Had one autostart process, `icc-brightness`, but killing that had no effect.

User systemd services:

* Solaar
* deja-dup-monitor
* gnome-software
* gsd-disk-utility-notify
* evolution-alarm-notify

These are all timer and event based services, so it could be one of them.  Have
to figure out how to temporarily disable the systemd user services to check
these -- they seem to like to respawn.

**Comment by tartansandal** [comment]
@kamilprusko Revelation! The problem disappears if I login with X11 instead of Wayland. 

That's good news since I can work in X11 for a while -- I have a few other programs that are currently struggling in Wayland. It would be good to get this sorted since Wayland is the default for Fedora. Does this issue stay here or should it be raised with the Wayland people?

**Comment by kamilprusko** [comment]
I didn't experience this with my integrated graphics card + wayland. My guess is it's related to the blur shader. If I'm right, if you played a video on one of the screens - that screen will be rendered ok. In other words - most recently rendered screen will be ok.

In new release [0.19.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.19.0) there is a new blur shader during break, which is vastly different. I think it should fix the issue.

Please close the ticket if it's solved.

**Comment by tartansandal** [comment]
Awesome! Very busy ATM. Will leave testing until Fedora 34 is released on 20th and which includes this. :)

**Comment by jurf** [comment]
Am currently running F34 with 0.19.0, and it looks like it’s fixed. 🙂 I did notice some small visual artefacts in the bottom right corner in a vertical dual-monitor setup, however, I’ll try to capture it later. The screens also bleed into themselves, but that might be intentional.

**Comment by tartansandal** [comment]
@kamilprusko Finally got to upgrade and the issue definitely seems to be fixed :partying_face: As @jurf noted, there are some visual artifacts on dual screen display, but I think that should be for another issue.
