### ISSUE TITLE
[Gnome 40] screen does not dim when break timer starts

### ISSUE THREAD

**Issue by sanjayankur31** [gnome-pomodoro/gnome-pomodoro#547]
## Issue Summary

This is for Gnome 40, which hasn't been released yet (so it's more of an early FYI :)). Fedora users can use [this COPR](https://copr.fedorainfracloud.org/coprs/haeckerfelix/gnome-shell-40/) to already test it out.

Here, when it's time for a break and the break timer starts, while the timer is visible in white font on the screen, the screen itself does not dim---making it hard to see the timer.

```

$ rpm -qa \*pomodoro\* gnome-shell
gnome-shell-extension-pomodoro-0.18.0-1.fc33.x86_64
gnome-shell-40.0~alpha.1.1-1.20210213.0.x86_64
```

## Steps to Reproduce

1. Install gnome-40
2. Run gnome-pomodoro as usual

## Context (logs, error output, screencast, OS, Desktop  etc)

The journal shows these messages:

```
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25
Feb 16 11:05:16 ankur.workstation gnome-shell[9194]: JS ERROR: TypeError: method Clutter.Effect.pre_paint: At least 2 arguments required, but only 1 passed
                                                     vfunc_pre_paint@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dialogs.js:170:25

```

Here's a screen cast: https://ankursinha.fedorapeople.org/misc/pomodoro-gnome-40.webm

## Expected Behavior

Screen should dim when break timer starts.

## Current Behavior

Screen does not dim when break timer starts.

## Possible Solution

Looks like a Gnome 40 change?

## Other information

NA

**Comment by kamilprusko** [comment]
Thanks for the report. I've started updating my jhbuild.

**Comment by kamilprusko** [comment]
This is fixed in [0.19.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.19.0).

@mbooth101 Letting you know there is a release for GNOME 4.0

**Comment by mbooth101** [comment]
@kamilprusko Thanks, however the gnome-shell extension fails to load on my Fedora 34 system (Gnome 40)

It looks like a typo in the gnome version number; I had to make the following change to make it work:

    sed -i -e 's/4.0/40.0/' plugins/gnome/extension/metadata.json.in

I have built gnome-pomodoro for Fedora 34+ with this change and it seems to work well otherwise :-)

**Comment by mbooth101** [comment]
Update submitted for F34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-5c7319d8a2

It should also be in tomorrow's Rawhide (F35)

**Comment by kamilprusko** [comment]
Thanks @mbooth101 ! :)
