### ISSUE TITLE
Error loading extension in GNOME Tweaks

### ISSUE THREAD

**Issue by PanderMusubi** [gnome-pomodoro/gnome-pomodoro#550]
## Issue Summary

The extensions tab of GNOME Tweaks reports an error for Pomodoro.

## Steps to Reproduce

1. Install GNOME Tweaks
2. Install GNOME Pomodoro
3. Open extensions tab in GNOME Tweaks

## Context (logs, error output, screencast, OS, Desktop  etc)

Version 3.34.0-4  for GNOME Tweaks and 0.17.0-1 for Pomorodo.

## Expected Behavior

Should be no error and the extensions can be enabled/disabled. Default is enabled.

## Current Behavior

See error in screenshot.

## Other information

Was reported first https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/343#note_1056203 but belongs here.

![Screenshot from 2021-03-12 13-46-47](https://user-images.githubusercontent.com/198964/110954377-b86d8000-8348-11eb-8b72-a9622c66098f.png)

**Comment by kamilprusko** [comment]
0.17.0 supports only GNOME 3.36

Try installing 0.16.0 https://github.com/gnome-pomodoro/gnome-pomodoro/tree/gnome-3.34 . Make sure to uninstall your previous version.

**Comment by PanderMusubi** [comment]
Thanks. In Hirsute Hippo this will probably be fixed with GNOME 3.38.4 and Pomodoro 0.18.0
