### ISSUE TITLE
Next Point Release? (GNOME 40)

### ISSUE THREAD

**Issue by liamtimms** [gnome-pomodoro/gnome-pomodoro#553]
Hi, I'm just filing this request because I'm currently maintaining the AUR `PKGBUILD` for this extension: https://aur.archlinux.org/packages/gnome-shell-pomodoro/ 

I'm not sure exactly when Arch will officially roll out GNOME 40 but I'm just checking if there is a plan for when to create the next point release for this extension. I can see the extension has been marked as compatible with GNOME 40 in the recent commits. Does that mean users who are installing it from the official extensions site will be able to update it without a problem? For the AUR, we'd need a new point release to be easily able to roll it out to users installing it through the Arch Build System. Are there plans for a new release soon? 

Thanks for all your hard work.

**Comment by Bsplesk** [comment]
Arch/Aur Pomidore
Linux mhome 5.10.26-1-lts #1 SMP Thu, 25 Mar 2021 08:56:04 +0000 x86_64 GNU/Linux
40.0.0
** (gnome-pomodoro:3532): CRITICAL **: 10:50:41.322: gnome-shell-extension.vala:314: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: ReloadExtension is deprecated and does not work
** (gnome-pomodoro:3532): WARNING **: 10:50:44.297: gnome-shell-extension.vala:404: Extension error: No JS module 'tweener' found in search path
** (gnome-pomodoro:3532): WARNING **: 10:50:44.298: application.vala:211: Failed to initialize plugin "gnome": Operation was cancelled

**Comment by liamtimms** [comment]
@Bsplesk I'm not sure I understand what you are trying to communicate here. Are these errors from the AUR build when used in GNOME 40?

**Comment by Bsplesk** [comment]
Yes. 

On the other hand, today I compiled a version from git and there are also errors there.
$ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>40</platform>
 <minor>0</minor>
 <micro>0</micro>
 <distributor>Arch Linux</distributor>
 
----------
** (gnome-pomodoro:29518): CRITICAL **: 15:54:43.563: gnome-shell-extension.vala:314: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: ReloadExtension is deprecated and does not work

** (gnome-pomodoro:29518): WARNING **: 15:54:46.534: gnome-shell-extension.vala:406: Extension error: No JS module 'tweener' found in search path

** (gnome-pomodoro:29518): WARNING **: 15:54:46.535: application.vala:211: Failed to initialize plugin "gnome": Operation was cancelled

(gnome-pomodoro:29518): Gtk-WARNING **: 15:55:04.922: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-pomodoro:29518): Gtk-WARNING **: 15:55:04.922: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-pomodoro:29518): Gtk-WARNING **: 15:55:04.922: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-pomodoro:29518): Gtk-WARNING **: 15:55:04.922: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-pomodoro:29518): Gtk-CRITICAL **: 15:55:04.964: gtk_stack_add_titled: assertion 'GTK_IS_STACK (stack)' failed

(gnome-pomodoro:29518): Gtk-CRITICAL **: 15:55:04.964: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by Bsplesk** [comment]
+
````
Mar 31 11:34:02 mhome systemd-coredump[26855]: Process 26437 (gnome-pomodoro) of user 1000 dumped core.
                                               
                                               Stack trace of thread 26437:
                                               #0  0x00007f624eddfcab gtk_widget_destroy (libgtk-3.so.0 + >
                                               #1  0x00007f624c44048f sounds_plugin_preferences_dialog_ext>
                                               #2  0x00007f624e46c801 g_object_unref (libgobject-2.0.so.0 >
                                               #3  0x00007f624e6b58b8 n/a (libpeas-1.0.so.0 + 0x68b8)
                                               #4  0x00007f624e45fddf g_closure_invoke (libgobject-2.0.so.>
                                               #5  0x00007f624e488fbd n/a (libgobject-2.0.so.0 + 0x3bfbd)
                                               #6  0x00007f624e47ccad g_signal_emit_valist (libgobject-2.0>
                                               #7  0x00007f624e47d210 g_signal_emit (libgobject-2.0.so.0 +>
                                               #8  0x00007f624e6ba676 peas_engine_unload_plugin (libpeas-1>
                                               #9  0x00007f624f27f30e pomodoro_application_real_shutdown (>
                                               #10 0x00007f624e47d096 g_signal_emit_valist (libgobject-2.0>
                                               #11 0x00007f624e47d210 g_signal_emit (libgobject-2.0.so.0 +>
                                               #12 0x00007f624e5b83ab g_application_run (libgio-2.0.so.0 +>
                                               #13 0x00005641a1cb331e _vala_main (gnome-pomodoro + 0x131e)
                                               #14 0x00005641a1cb337d main (gnome-pomodoro + 0x137d)
                                               #15 0x00007f624e00ab25 __libc_start_main (libc.so.6 + 0x27b>
                                               #16 0x00005641a1cb310e _start (gnome-pomodoro + 0x110e)
````

**Comment by liamtimms** [comment]
This is expected for the AUR PKGBUILD since there isn't a new point release yet (hence me opening this issue to ask about it). If the git version is also not working then it probably isn't fully compatible with 40 yet and I read too much into one of the commits. We need to allow time for the extension developers to update accordingly. Looking at the release history it might take a week or two. We'll see when the Arch devs decide to roll 40 out to general users but I expect they may be waiting to give time for major extensions to catch up.

**Comment by kamilprusko** [comment]
@liamtimms Created tag https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.19.0 . Thanks for raising the issue.

@Bsplesk this is to be expected as extension is outdated. Thanks for reporting the
> ReloadExtension is deprecated and does not work

It's just a warning and there is no solution. Likely I will replace it with notification, suggesting to log out or reboot... Relevant issue in gnome-shelll: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2510

**Comment by liamtimms** [comment]
@kamilprusko thanks, it seems that this release is still showing up as incompatible with GNOME 40  due to the version check. Do you recommend that I wait for the next release for more GNOME 40 fixes or do you recommend that I provide a patch (using 0952054d35e9c9c7073ff8918b82b849b6eccc28) for users in the build process so that they can enable the extension in 40 now?

**Comment by kamilprusko** [comment]
@liamtimms I tagged it as [0.19.1](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.19.1) - it just contains that version patch.

**Comment by liamtimms** [comment]
@kamilprusko perfect, it's running on my machine now and I'm pushing it out to users. Thank you for all your hard work.
