### ISSUE TITLE
[Feature] Ability to hide the giant "down arrow" indicator icon

### ISSUE THREAD

**Issue by Bananaman** [gnome-pomodoro/gnome-pomodoro#555]
## Is your proposal related to a problem?

You have created an incredibly beautiful application with such elegant design. I only wish there was a way to hide the massive downarrow which takes up a lot of space and is so heavy that it stands out like a sore thumb:

![gianticon](https://user-images.githubusercontent.com/38923130/116168861-b5193280-a703-11eb-8ecb-8975d2d733cb.png)

The downarrow serves no purpose for experienced users and just takes up space. Other people have used workarounds, but there is sadly no "remove downarrow icons" extension for GNOME 40, so I can't do what previous users did: https://github.com/gnome-pomodoro/gnome-pomodoro/issues/228

## Describe the solution you'd like

I see that you're creating the arrow here:

https://github.com/gnome-pomodoro/gnome-pomodoro/blob/0952054d35e9c9c7073ff8918b82b849b6eccc28/plugins/gnome/extension/indicator.js#L627

Hiding it via a preference is as easy as toggling the visibility of the arrow icon, like this (example from the great Clipboard extension):

https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/fc9eebd1e9f91727892d6b3fa6f9d08078523e89/extension.js#L781-L785

That project triggers the arrow visibility update-function (they've named it `_updateTopbarLayout()` as seen above) on both `_init()` and `_onSettingsChange()`.

As a result, it supports hiding/unhiding the arrow live.

Such a feature would be beautiful in Pomodoro timer. To get rid of the giant downarrow, for people who prefer a cleaner desktop.

## Describe alternatives you've considered

There are no downarrow fixes on GNOME 40. And there's no time tracker that's as good as this lovely Pomodoro extension!

## Other information

I would try to mod this extension myself but would screw it up since I don't know the codebase. :-P

**Comment by kamilprusko** [comment]
Arrow is removed in branch [gnome-4.0](https://github.com/gnome-pomodoro/gnome-pomodoro/commits/gnome-4.0). Patch will be included in next point release (0.19.2).

It took me a while to notice that GNOME Shell 40 no longer uses dropdown arrows :joy: in 3.xx arrows could be removed globally with this extension: https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows , so I didn't see a need for a setting/toggle.

Thanks for reporting the issue and suggestions.

**Comment by Bananaman** [comment]
@kamilprusko Ah that is great news, thank you so much. And thanks again for making this incredible extension! 😍
