### ISSUE TITLE
Package dependencies URL's return 404 errors

### ISSUE THREAD

**Issue by Alonoparag** [gnome-pomodoro/gnome-pomodoro#557]
makepkg -s
==> Making package: gnome-shell-pomodoro 0.19.1-1 (Sun 02 May 2021 16:09:35)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (3) python-beaker-1.11.0-6  python-mako-1.1.4-1
             gobject-introspection-1.68.0-1

Total Installed Size:  14.53 MiB

:: Proceed with installation? [Y/n] y
(3/3) checking keys in keyring                     [######################] 100%
(3/3) checking package integrity                   [######################] 100%
(3/3) loading package files                        [######################] 100%
(3/3) checking for file conflicts                  [######################] 100%
(3/3) checking available disk space                [######################] 100%
:: Processing package changes...
(1/3) installing python-beaker                     [######################] 100%
(2/3) installing python-mako                       [######################] 100%
(3/3) installing gobject-introspection             [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (12) autoconf-archive-1:2019.01.06-4  itstool-1:2.0.6-2
              mallard-ducktype-1.0.2-6  openjade-1.3.2-6  opensp-1.5.2-9
              perl-sgmls-1:1.1-7  sgml-common-0.6.3-7  yelp-tools-40.0-1
              docbook2x-0.8.8-17  gnome-common-3.18.0-4  intltool-0.51.0-6
              perl-xml-sax-expat-0.51-7

Total Download Size:    0.28 MiB
Total Installed Size:  11.32 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from ftp.tu-chemnitz.de : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from mirror.easylee.nl : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from manjaro.mirrors.lavatech.top : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from mirror.koddos.net : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from mirror.atysleaks.org : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from ftp.dei.uc.pt : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from mirror.terrahost.no : The requested URL returned error: 404
error: failed retrieving file 'docbook2x-0.8.8-17-x86_64.pkg.tar.zst' from kartolo.sby.datautama.net.id : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> intltool
  -> gnome-common
  -> docbook2x
  -> perl-xml-sax-expat
==> ERROR: Could not resolve all dependencies.

**Comment by bbo2adwuff** [comment]
This is not a gnome-pomodoro issue. Somehow your arch's `pacman` returns 404 for `docbook2x-0.8.8-17-x86_64.pkg.tar.zst`. So you should check your pacman. Did you try `sudo pacman -Syyuu` before trying to install from the PKGBUILD from `aur`?

**Comment by Alonoparag** [comment]
I did, it now give another error:

==> Starting prepare()...
sed: can't read configure.ac: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
error making: gnome-pomodoro-git

**Comment by Alonoparag** [comment]
Solved
