### ISSUE TITLE
No system tray icon on Ubuntu 21.04

### ISSUE THREAD

**Issue by drazik** [gnome-pomodoro/gnome-pomodoro#558]
## Issue Summary

After upgrading Ubuntu to v21.04, the system tray icon doesn't show anymore. Thus there is no access to its contextual menu.

## Steps to Reproduce

1. Start `gnome-pomodoro`

## Context (logs, error output, screencast, OS, Desktop  etc)

I was running Ubuntu 20.10 in which the icon was present and everything worked well. I upgraded to Ubuntu 21.04 and it disappeared.

## Expected Behavior

An icon should be present in the system tray (little bar at the top of the screen)

![image](https://user-images.githubusercontent.com/1606068/118268049-29eabb80-b4bd-11eb-86d1-db05335edb97.png)

## Current Behavior

The icon doesn't appear

## Possible Solution

Absolutely no idea, sorry

**Comment by lacostenycoder** [comment]
try using [genome tweak tool](https://pkgs.org/download/gnome-tweak-tool)
then open the app `super key > tweak` then goto Extensions and enable Pomodoro
You should now see the icon on the status bar.

**Comment by drazik** [comment]
Thanks for your answer. I don't understand why I should install Gnome though. I thought Ubuntu 21.04 was using gnome as its desktop environment. I am wrong?

**Comment by alcarraz** [comment]
You don't need to install gnome, just enable the Pomodoro extension.

**Comment by drazik** [comment]
Oh OK I didn't understand that. It works now, thanks!
