### ISSUE TITLE
How to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by t1ooo** [gnome-pomodoro/gnome-pomodoro#570]
Hello. I am trying to build with command

```$ ./autogen.sh --prefix=/usr --datadir=/usr/share```

and get an error

```*** ERROR: Directory `.' does not look like the top-level project directory ***```

Thanks.

**Comment by Arpitchugh** [comment]
Try using command directly in your terminal -> 
 sudo apt-get install gnome-shell-pomodoro

**Comment by bbo2adwuff** [comment]
Just stumbled upon this issue as well.

In this commit 9afecf74a67f49eebfba203d661e25b77937593c `configure.ac` was removed. So `./autogen.sh` simply cannot work. See following line:
https://github.com/gnome-pomodoro/gnome-pomodoro/blob/e97008672509a3c1d7b08311bd92e71af13e7691/autogen.sh#L9

**Quick and dirty solution?**
If you still want to use Autotools just revert 9afecf74a67f49eebfba203d661e25b77937593c and it works :grin: Or switch to another branch as this was just commited to `master`, but none of the other branches.
