### ISSUE TITLE
Option to invert dropdown arrow icon

### ISSUE THREAD

**Issue by robertpiosik** [gnome-pomodoro/gnome-pomodoro#573]
## Is your proposal related to a problem?

Arrow looks inconsistent when top bar is docked at the bottom of the screen.

## Describe the solution you'd like

Ability to set arrow direction by a toggle option.

## Other information

![image](https://user-images.githubusercontent.com/7120725/127402054-401ee140-2a5a-49f3-aad8-886409994055.png)

**Comment by kamilprusko** [comment]
Sorry, forgot to close the issue.

Since GNOME Shell 40, the arrow is removed.
