### ISSUE TITLE
SyntaxError: expected expression, got '<' @ dbus.js:23

### ISSUE THREAD

**Issue by kstefanini** [gnome-pomodoro/gnome-pomodoro#579]
## Issue Summary

Hi! Already an happy user of Pomodo on Ubuntu, I tried to install on Pop!_OS 21.04 from https://extensions.gnome.org/extension/53/pomodoro/
But I got this error:
```
JS ERROR: Extension pomodoro@arun.codito.in: SyntaxError: expected expression, got '<' @ /home/user/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/dbus.js:23
```

What can I do?
Thanks for you help :)

## Steps to Reproduce

1. Install from https://extensions.gnome.org/extension/53/pomodoro/ on Pop!_OS 21.04

## Context (logs, error output, screencast, OS, Desktop  etc)

System:
Pop!_OS 21.04
Gnome 3.38
X11

Log:
```
JS ERROR: Extension pomodoro@arun.codito.in: SyntaxError: expected expression, got '<' @ /home/user/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/dbus.js:23
```
dbus.js partial code (line 23 is "const PomodoroTimerIface"...):
```
const Signals = imports.signals;


const PomodoroTimerIface = <interface name="org.gnome.Shell.Extensions.Pomodoro">
<method name="Start"/>
<method name="Stop"/>
<method name="Reset"/>
```

**Comment by kstefanini** [comment]
Ok, just found I just had to run `sudo apt-get install gnome-shell-pomodoro` to get a working solution.
What's wrong with the extensions.gnome.org version?

**Comment by mbooth101** [comment]
The version on extensions.gnome.org is very old and no longer maintained. (This is noted on the gnomepomodoro.org website.)

**Comment by mbooth101** [comment]
Haha, I just noticed it even says this on https://extensions.gnome.org/extension/53/pomodoro/

> NOTICE
> New versions are no longer distributed through extensions.gnome.org. Look for "pomodoro" in your distros repositories or grab package from http://gnomepomodoro.org

**Comment by kstefanini** [comment]
Oh right, I see it now. 
Sorry for that
