### ISSUE TITLE
Fedora 35/Gnome 40 on Wayland: Keyboard short no longer works

### ISSUE THREAD

**Issue by sanjayankur31** [gnome-pomodoro/gnome-pomodoro#585]
## Issue Summary

Describe your issue here.
The keyboard shortcut we set in preferences no longer seems to work. This is likely some Gnome/Wayland issue, but since I haven't been able to narrow it down, I thought I'd at least file a ticket here.

## Steps to Reproduce

1. Try using the keyboard shortcuts to start/stop gnome-pomodoro
2. Try changing the keyboard shortcuts to a new combination in preferences
3. Try using the new shortcuts

## Context (logs, error output, screencast, OS, Desktop  etc)

https://ankursinha.fedorapeople.org/misc/Screencast-pomodoro-f35.webm

(I'm hitting the key combination after setting it there, but nothing happens)

## Expected Behavior

Should work

## Current Behavior

Doesn't work

## Possible Solution

Not sure at the moment. Tested it out on two machines, with a new user too, and get the same result. Works on X11, though, so could be related to Wayland?

## Other information

$ rpm -qa \*wayland\* \*pomodoro\* \*shell\*
libwayland-client-1.19.0-2.fc35.x86_64
libwayland-server-1.19.0-2.fc35.x86_64
libwayland-egl-1.19.0-2.fc35.x86_64
libwayland-cursor-1.19.0-2.fc35.x86_64
xorg-x11-server-Xwayland-21.1.2-2.fc35.x86_64
gnome-session-wayland-session-40.1.1-2.fc35.x86_64
gnome-pomodoro-0.19.2-0.3.fc35.x86_64
chrome-gnome-shell-10.1-14.fc35.x86_64
gnome-shell-extension-background-logo-40.0~rc-3.fc35.noarch
qt5-qtwayland-5.15.2-11.fc35.x86_64
gnome-shell-41.0-1.fc35.x86_64
gnome-shell-extension-common-41.0-1.fc35.noarch
gnome-shell-extension-user-theme-41.0-1.fc35.noarch

**Comment by kamilprusko** [comment]
It might got broken in GNOME 41. Will look into that.

**Comment by sanjayankur31** [comment]
Thanks very much. It could even be something wrong on the Gnome side of things. I'm seeing a few other issues here too (with Zoom and Qt apps).

**Comment by mbooth101** [comment]
> gnome-pomodoro-0.19.2-0.3.fc35.x86_64

You do not have the latest. Is it still a problem with gnome-pomodoro-0.20.0 from updates-testing repo?

```
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-334ee02b27
```

**Comment by sanjayankur31** [comment]
> > gnome-pomodoro-0.19.2-0.3.fc35.x86_64
> 
> You do not have the latest. Is it still a problem with gnome-pomodoro-0.20.0 from updates-testing repo?
> 
> ```
> sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-334ee02b27
> ```

When I resumed both my systems from suspend this morning, ctrl alt p now works as expected. So not quite sure what's causing it.

I've updated to the updates-testing version now and will keep an eye out for the issue again. Closing this for the time being.
