### ISSUE TITLE
Literally doesn't open (gnome-pomodoro: error while loading shared libraries: libgnome-pomodoro.so.0: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by hrqmonteiro** [gnome-pomodoro/gnome-pomodoro#594]
Built from source and installed, when i try to open i have this:

```
gnome-pomodoro: error while loading shared libraries: libgnome-pomodoro.so.0: cannot open shared object file: No such file or directory
```

**Comment by kamilprusko** [comment]
I don't know why it happens...

Check if there were no install errors. If everything seems ok, check if libgnome-pomodoro.so.0.0.0 got installed
```
$ whereis gnome-pomodoro
gnome-pomodoro: /usr/bin/gnome-pomodoro /usr/lib64/gnome-pomodoro /usr/share/gnome-pomodoro /usr/share/man/man1/gnome-pomodoro.1
```
In the example above, `libgnome-pomodoro.so.0.0.0` should be in `/usr/lib64/gnome-pomodoro/`.

Then as a workaround, create the missing symbolic link yourself
```
cd /usr/lib64/gnome-pomodoro/
sudo ln -s libgnome-pomodoro.so.0.0.0 libgnome-pomodoro.so.0
```

**Comment by caioolivv** [comment]
I'm having the same problem and the solution provided doesn't work for me.

 `whereis gnome-pomodoro` returns `gnome-pomodoro: /usr/local/lib/x86_64-linux-gnu/gnome-pomodoro /usr/local/bin/gnome-pomodoro`. 

The only content of `/usr/local/lib/x86_64-linux-gnu/gnome-pomodoro` is the `plugin` directory. 

However, `/usr/local/lib/x86_64-linux-gnu` contains `gnome-pomodoro`, `gnome-pomodoro`, `libgnome-pomodoro.so.0` and `libgnome-pomodoro.so.0.0.0`. How should I proceed?

**Comment by caioolivv** [comment]
> I'm having the same problem and the solution provided doesn't work for me.
> 
> `whereis gnome-pomodoro` returns `gnome-pomodoro: /usr/local/lib/x86_64-linux-gnu/gnome-pomodoro /usr/local/bin/gnome-pomodoro`.
> 
> The only content of `/usr/local/lib/x86_64-linux-gnu/gnome-pomodoro` is the `plugin` directory.
> 
> However, `/usr/local/lib/x86_64-linux-gnu` contains `gnome-pomodoro`, `gnome-pomodoro`, `libgnome-pomodoro.so.0` and `libgnome-pomodoro.so.0.0.0`. How should I proceed?

Simply moving `gnome-pomodoro`, `libgnome-pomodoro.so.0` and `libgnome-pomodoro.so.0.0.0` to `/usr/local/lib/x86_64-linux-gnu/gnome-pomodoro` solved it.

**Comment by rodrigogonegit** [comment]
Running strace gnome-pomodoro shows that it is attempting to import the lib from these locations: 

```
/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/tls/haswell/x86_64/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/tls/haswell/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/tls/x86_64/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/tls/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/haswell/x86_64/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/haswell/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/x86_64/libgnome-pomodoro.so.0
/lib/x86_64-linux-gnu/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/tls/haswell/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/tls/x86_64/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/tls/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/haswell/x86_64/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/haswell/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/x86_64/libgnome-pomodoro.so.0
/usr/lib/x86_64-linux-gnu/libgnome-pomodoro.so.0
/lib/glibc-hwcaps/x86-64-v3/libgnome-pomodoro.so.0
/lib/glibc-hwcaps/x86-64-v2/libgnome-pomodoro.so.0
/lib/tls/haswell/x86_64/libgnome-pomodoro.so.0
/lib/tls/haswell/libgnome-pomodoro.so.0
/lib/tls/x86_64/libgnome-pomodoro.so.0
/lib/tls/libgnome-pomodoro.so.0
/lib/haswell/x86_64/libgnome-pomodoro.so.0
/lib/haswell/libgnome-pomodoro.so.0
/lib/x86_64/libgnome-pomodoro.so.0
/lib/libgnome-pomodoro.so.0
/usr/lib/glibc-hwcaps/x86-64-v3/libgnome-pomodoro.so.0
/usr/lib/glibc-hwcaps/x86-64-v2/libgnome-pomodoro.so.0
/usr/lib/tls/haswell/x86_64/libgnome-pomodoro.so.0
/usr/lib/tls/haswell/libgnome-pomodoro.so.0
/usr/lib/tls/x86_64/libgnome-pomodoro.so.0
/usr/lib/tls/libgnome-pomodoro.so.0
/usr/lib/haswell/x86_64/libgnome-pomodoro.so.0
/usr/lib/haswell/libgnome-pomodoro.so.0
/usr/lib/x86_64/libgnome-pomodoro.so.0
/usr/lib/libgnome-pomodoro.so.0

```
When in fact the file is located in `/usr/local/lib/x86_64-linux-gnu/gnome-pomodoro/`.
Copying libgnome-pomodoro.so.0 to any of the target locations should work, I copied it to `/usr/lib/x86_64-linux-gnu/`, so just run: 

`sudo cp /usr/local/lib/x86_64-linux-gnu/libgnome-pomodoro.so.0 /usr/lib/x86_64-linux-gnu/`

**Comment by kamilprusko** [comment]
Thanks @rodrigogonegit for the strace log.

It may be a meson > 0.56.0 issue: https://github.com/mesonbuild/meson/issues/8561

From what I understand, libdir normally is baked into executable as one of the search paths for the .so. I confirm that installing gnome-pomodoro into non-standard prefix causes this issue, and /usr/local seems to be non-standard.

To avoid this issue, cleanest workaround is installing into /usr prefix for now.

To uninstall from old prefix:
```
$ meson build-usr-local
$ cd build-usr-local
$ meson configure --prefix=/usr/local
$ meson compile
$ sudo ninja uninstall
```

To install it in /usr:
```
$ meson build-usr
$ cd build-usr
$ meson configure --prefix=/usr
$ meson compile
$ sudo meson install
```

**Comment by collins-lagat** [comment]
@kamilprusko Thanks. This workaround worked.
