### ISSUE TITLE
Pomodoro Freezes on Fedora 35

### ISSUE THREAD

**Issue by icfmp** [gnome-pomodoro/gnome-pomodoro#602]
## Issue Summary

Pomodoro freezes on launch.

## Steps to Reproduce

1. Start Pomodoro
2. It frezees

## Context (logs, error output, screencast, OS, Desktop  etc)

Fedora 35 (upgraded from Fedora 34)

## Expected Behavior

It should work.

## Current Behavior
It does not work.

## Possible Solution

It seems to be related to libnotification.so

![Capture d’écran de 2021-11-22 13-47-29](https://user-images.githubusercontent.com/71736258/142865446-8171a413-7fe1-41e3-ba94-3769ebf7ff2e.png)

**Comment by gdelacruzfdez** [comment]
Same issue on Manjaro 21.2

**Comment by mbooth101** [comment]
What version of gnome-pomodoro do you have installed?

Post the output of: `rpm -q gnome-pomodoro`

**Comment by xsebek** [comment]
Mine is the latest  `gnome-pomodoro-1:0.20.0-1.fc35.x86_64`, though it does not mention any plugins as OP:
![](https://user-images.githubusercontent.com/44544735/143861693-508beb72-9d26-4fc6-b22f-709c52cb6811.png)

The same happens with build from source.

**Comment by icfmp** [comment]
Same here

**Comment by l-ray** [comment]
**Potential work-around**: 

1. Go to https://extensions.gnome.org/extension/53/pomodoro/ (with a browser allowing to install Gnome extensions) 
2. Allow showing all versions (not just the compatible ones), now the on/off switch should appear
3. Install the extension

For me now extension and full program work as expected. /shrug

**Comment by hansmorb** [comment]
Same issue on my system:

> System:
  Kernel: 5.15.0-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0
  parameters: BOOT_IMAGE=/boot/vmlinuz-5.15-x86_64
  root=UUID=f54f97ce-0481-4e33-991c-8c70989bbb74 rw quiet splash apparmor=1
  security=apparmor udev.log_priority=3
  Desktop: GNOME 40.5 tk: GTK 3.24.30 wm: gnome-shell dm: GDM 40.1
  Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Laptop System: ASUSTeK product: UX410UAK v: 1.0 serial: <filter>
  Mobo: ASUSTeK model: UX410UAK v: 1.0 serial: <filter>
  UEFI: American Megatrends v: UX410UAK.308 date: 11/08/2017
Battery:
  ID-1: BAT0 charge: 36.1 Wh (96.5%) condition: 37.4/48.3 Wh (77.4%)
  volts: 11.4 min: 11.4 model: ASUSTeK ASUS Battery type: Li-ion serial: N/A
  status: Discharging cycles: 695
Memory:
  RAM: total: 7.65 GiB used: 3.15 GiB (41.1%)
  RAM Report: permissions: Unable to run dmidecode. Root privileges required.
CPU:
  Info: Dual Core model: Intel Core i5-7200U bits: 64 type: MT MCP
  arch: Amber/Kaby Lake note: check family: 6 model-id: 8E (142) stepping: 9
  microcode: EA cache: L2: 3 MiB bogomips: 21607
  Speed: 900 MHz min/max: 400/3100 MHz Core speeds (MHz): 1: 900 2: 900 3: 900
  4: 900
  Flags: 3dnowprefetch abm acpi adx aes aperfmperf apic arat arch_perfmon art
  avx avx2 bmi1 bmi2 bts clflush clflushopt cmov constant_tsc cpuid
  cpuid_fault cx16 cx8 de ds_cpl dtes64 dtherm dts epb ept ept_ad erms est
  f16c flexpriority flush_l1d fma fpu fsgsbase fxsr ht hwp hwp_act_window
  hwp_epp hwp_notify ibpb ibrs ida intel_pt invpcid invpcid_single lahf_lm lm
  mca mce md_clear mmx monitor movbe mpx msr mtrr nonstop_tsc nopl nx pae pat
  pbe pcid pclmulqdq pdcm pdpe1gb pebs pge pln pni popcnt pse pse36 pti pts
  rdrand rdseed rdtscp rep_good sdbg sep smap smep ss ssbd sse sse2 sse4_1
  sse4_2 ssse3 stibp syscall tm tm2 tpr_shadow tsc tsc_adjust
  tsc_deadline_timer vme vmx vnmi vpid x2apic xgetbv1 xsave xsavec xsaveopt
  xsaves xtopology xtpr
  Vulnerabilities: Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf
  mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable
  Type: mds mitigation: Clear CPU buffers; SMT vulnerable
  Type: meltdown mitigation: PTI
  Type: spec_store_bypass
  mitigation: Speculative Store Bypass disabled via prctl and seccomp
  Type: spectre_v1
  mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional,
  IBRS_FW, STIBP: conditional, RSB filling
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel HD Graphics 620 vendor: ASUSTeK driver: i915 v: kernel
  bus-ID: 00:02.0 chip-ID: 8086:5916 class-ID: 0300
  Device-2: Chicony USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  bus-ID: 1-6:2 chip-ID: 04f2:b57a class-ID: 0e02 serial: <filter>
  Display: wayland server: X.org 1.20.13 compositor: gnome-shell driver:
  loaded: modesetting alternate: fbdev,vesa display-ID: 0
  resolution: <missing: xdpyinfo>
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.2.3
  direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: ASUSTeK
  driver: snd_hda_intel v: kernel alternate: snd_soc_skl bus-ID: 00:1f.3
  chip-ID: 8086:9d71 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-1-MANJARO running: yes
  Sound Server-2: JACK v: 1.9.19 running: no
  Sound Server-3: PulseAudio v: 15.0 running: yes
  Sound Server-4: PipeWire v: 0.3.38 running: no
Network:
  Device-1: Intel Wireless 8260 driver: iwlwifi v: kernel bus-ID: 02:00.0
  chip-ID: 8086:24f3 class-ID: 0280
  IF: wlp2s0 state: up mac: <filter>
  IP v4: <filter> type: dynamic noprefixroute scope: global
  broadcast: <filter>
  IP v6: <filter> type: noprefixroute scope: link
  WAN IP: <filter>
Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8
  bus-ID: 1-8:3 chip-ID: 8087:0a2b class-ID: e001
  Report: rfkill ID: hci0 rfk-id: 1 state: up address: see --recommends
Logical:
  Message: No logical block device data found.
RAID:
  Message: No RAID data found.
Drives:
  Local Storage: total: 2.73 TiB used: 955.48 GiB (34.2%)
  SMART Message: Required tool smartctl not installed. Check --recommends
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Kingston model: SA2000M81000G
  size: 931.51 GiB block-size: physical: 512 B logical: 512 B speed: 31.6 Gb/s
  lanes: 4 type: SSD serial: <filter> rev: S5Z42105 temp: 24.9 C scheme: GPT
  ID-2: /dev/sda maj-min: 8:0 vendor: SanDisk model: SDSSDH3 2T00
  size: 1.82 TiB block-size: physical: 512 B logical: 512 B speed: 6.0 Gb/s
  type: SSD serial: <filter> rev: 20RL
  Message: No optical or floppy data found.
Partition:
  ID-1: / raw-size: 784.92 GiB size: 771.52 GiB (98.29%)
  used: 295.73 GiB (38.3%) fs: ext4 dev: /dev/nvme0n1p5 maj-min: 259:5
  label: N/A uuid: f54f97ce-0481-4e33-991c-8c70989bbb74
  ID-2: /boot/efi raw-size: 100 MiB size: 96 MiB (96.00%)
  used: 29.5 MiB (30.8%) fs: vfat dev: /dev/nvme0n1p1 maj-min: 259:1
  label: N/A uuid: 12F9-AA0A
  ID-3: /mnt/6ED64665D6462E21 raw-size: 1.82 TiB size: 1.82 TiB (100.00%)
  used: 659.72 GiB (35.4%) fs: ntfs dev: /dev/sda1 maj-min: 8:1 label: N/A
  uuid: 6ED64665D6462E21
Swap:
  Kernel: swappiness: 60 (default) cache-pressure: 100 (default)
  ID-1: swap-1 type: file size: 9.77 GiB used: 0 KiB (0.0%) priority: -2
  file: /swapfile
Unmounted:
  ID-1: /dev/nvme0n1p2 maj-min: 259:2 size: 16 MiB fs: <superuser required>
  label: N/A uuid: N/A
  ID-2: /dev/nvme0n1p3 maj-min: 259:3 size: 145.98 GiB fs: ntfs label: N/A
  uuid: 62700C0E700BE79D
  ID-3: /dev/nvme0n1p4 maj-min: 259:4 size: 515 MiB fs: ntfs label: N/A
  uuid: 9C8EABE18EABB266
USB:
  Hub-1: 1-0:1 info: Full speed (or root) Hub ports: 12 rev: 2.0
  speed: 480 Mb/s chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Chicony USB2.0 HD UVC WebCam type: Video
  driver: uvcvideo interfaces: 2 rev: 2.0 speed: 480 Mb/s power: 500mA
  chip-ID: 04f2:b57a class-ID: 0e02 serial: <filter>
  Device-2: 1-8:3 info: Intel Bluetooth wireless interface type: Bluetooth
  driver: btusb interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 100mA
  chip-ID: 8087:0a2b class-ID: e001
  Hub-2: 2-0:1 info: Full speed (or root) Hub ports: 6 rev: 3.0 speed: 5 Gb/s
  chip-ID: 1d6b:0003 class-ID: 0900
Sensors:
  System Temperatures: cpu: 36.0 C mobo: N/A
  Fan Speeds (RPM): cpu: 2600
Info:
  Processes: 226 Uptime: 16m wakeups: 1 Init: systemd v: 249 tool: systemctl
  Compilers: gcc: 11.1.0 Packages: 1482 pacman: 1471 lib: 462 flatpak: 0
  snap: 11 Shell: Zsh v: 5.8 running-in: gnome-terminal inxi: 3.3.08

**Comment by pomg** [comment]
> Allow showing all versions (not just the compatible ones), now the on/off switch should appear

If this step is a little bit confusing, you might try the following command in terminal and then refresh the page.

`gsettings get org.gnome.shell disable-extension-version-validation true` 

 Even though there will be an error on the extension page, the application will be working as expected.

**Comment by xsebek** [comment]
> If this step is a little bit confusing, you might try the following command in terminal and then refresh the page.
> `gsettings set org.gnome.shell disable-extension-version-validation true`

Enabling the extension helped me too! :+1:

If it is in fact required, maybe it could be set by the package?

Doing it manually feels like a weird hack, but I am happy it works :slightly_smiling_face:

**Comment by CLNRMN** [comment]
https://github.com/gnome-pomodoro/gnome-pomodoro/issues/608#issuecomment-1027744138 worked for me (fedora 35).

**Comment by mbledkowski** [comment]
> **Potential work-around**:
> 
>     1. Go to https://extensions.gnome.org/extension/53/pomodoro/ (with a browser allowing to install Gnome extensions)
> 
>     2. Allow showing all versions (not just the compatible ones), now the on/off switch should appear
> 
>     3. Install the extension by selecting "on"
> 
> 
> For me now extension and full program work as expected. /shrug

no idea how, but it works

**Comment by jtsilverio** [comment]
> 

It did work for me, thanks! I am also on fedora 35.

 So the app needs the extension to work properly? In order distros is the extension installed with the package?

**Comment by mbledkowski** [comment]
> > 
> 
> It did work for me, thanks! I am also on fedora 35.
> 
> So the app needs the extension to work properly? In order distros is the extension installed with the package?

on arch it is not

**Comment by s4ln1x** [comment]
On fedora 35 also running the following command allows you to run gnome-pomodoro, not sure what the root issue could be.

`gnome-extensions enable pomodoro@arun.codito.in`

**Comment by kamilprusko** [comment]
As @s4ln1x says, enabling the extension before running the app helps.

Fixed in [0.21.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.21.0) release.
