### ISSUE TITLE
Show lock-screen once it disapear

### ISSUE THREAD

**Issue by gj84** [gnome-pomodoro/gnome-pomodoro#603]
Hi, I really like this software. One of the thing I like the most is the lock-screen (in my case is just the screen shadowed with the rest clock). When I click on the screen or just move the mouse then the screen disapear. What I would like is a way to recover it while rest time is running, because is very nice to see it from distance.

**Comment by kamilprusko** [comment]
As @abrac said, clicking the timer will bring it back. In master branch I've added a hover effect:

![Screenshot from 2023-02-26 16-30-56](https://user-images.githubusercontent.com/1135423/222969230-69103471-3a53-4b4e-a6e1-075f7775daa9.png)

Also, clicking on notification will bring it back.
