### ISSUE TITLE
GNOME Shell 42 support in the extension

### ISSUE THREAD

**Issue by kappa** [gnome-pomodoro/gnome-pomodoro#608]
## Is your proposal related to a problem?

GNOME Pomodoro Shell extension does not work in recent GNOME Shell 42 which is going to be released in March.

## Describe the solution you'd like

Add "42" to metadata.json, test.

## Other information

Pomodoro app itself seems to work fine in GNOME 42.

**Comment by kappa** [comment]
Naive fix failed for with "Clutter.get_default_frame_rate is not a function" error message. Some changes in the extension code will be needed to support 42.

**Comment by abettati** [comment]
This is true also with Gnome Shell 40.4 (i.e. no icon in the taskbar under Ubuntu 21.10)

**Comment by bbo2adwuff** [comment]
@abettati Here it works, but after I updated `gnome-shell` I had to reinstall `gnome-pomodoro`.

If it still doesn't work after that you should check if the extension is disabled:
```
gnome-extensions info pomodoro@arun.codito.in
```
If yes, then enable:
```
gnome-extensions enable pomodoro@arun.codito.in
```

**Comment by abettati** [comment]
@bbo2adwuff thanks, but I tried and it is still not working.
I can see pomodoro in extensions, but it has a red cross and the description reads:
`The extension is incompatible with the current GNOME version`

My current gnome version is, more precisely, `40.4.0`

**Comment by mbooth101** [comment]
> (pomodoro version is 0.18)

You need to use the latest version for gnome 40 support. The version shipped with Fedora 35 is 0.20.0:

    $ rpm -q gnome-pomodoro
    gnome-pomodoro-0.20.0-1.fc35.x86_64

**Comment by abettati** [comment]
Ok, the problem then is that ubuntu points to the old `0.18`

**Comment by mbooth101** [comment]
> Ok, the problem then is that ubuntu points to the old `0.18`

Ah, in that case you should file a bug with Ubuntu to update their package :-)
