### ISSUE TITLE
No icon in top bar

### ISSUE THREAD

**Issue by lpalazzi** [gnome-pomodoro/gnome-pomodoro#613]
## Issue Summary

Installing on PopOS 21.10 (GNOME 40.4.0) does not show the icon in the top bar like it used to. I tried installing through `sudo apt install` as well as building from source. 

## Steps to Reproduce

1. Install Pomodoro on PopOS 21.10
2. Open Pomodoro

## Expected Behavior

Icon in top bar shows

## Current Behavior

No icon in top bar

## Other information

Switched to installing this way since the GNOME extension is now outdated on extensions.gnome.org

**Comment by lpalazzi** [comment]
@kamilprusko  Did the first two items, but I can't enable the extension through the extension app (see below)

![image](https://user-images.githubusercontent.com/33534854/154519819-28fa4684-3db5-4473-bfc9-e30d962ded98.png)

**Comment by logrusx** [comment]
@lpalazzi see what text is displayed when you expand the item pressing the right arrow.

**Comment by lpalazzi** [comment]
@logrusx 

My GNOME version is 40.4.0

![image](https://user-images.githubusercontent.com/33534854/155151252-3126b59b-b951-4401-9066-1c6552a61b0d.png)

**Comment by lpalazzi** [comment]
@logrusx How can I install a newer version?

**Comment by logrusx** [comment]
@lpalazzi try thus [https://www.reddit.com/r/pop_os/comments/obhnx9/pomodoro_not_in_topbar_anymore/](url). If it doesn't help, go to Pop OS' support/community forums, chats et.c. It's not the place here to ask for support on your OS.

**Comment by willosdalb** [comment]
yup same issue here.

**Comment by logrusx** [comment]
@willosdalb same answer from above.

**Comment by willosdalb** [comment]
i just disabled the version restriction on Gnome Extensions and it worked :)

**Comment by benhbell** [comment]
yea, this helped after @willosdalb comment. https://www.maketecheasier.com/disable-extension-version-checks-gnome/

**Comment by logrusx** [comment]
This issue should not be relevant anymore and therefore should be closed.
