### ISSUE TITLE
Break duration is seconds

### ISSUE THREAD

**Issue by musamaanjum** [gnome-pomodoro/gnome-pomodoro#614]
## Is your proposal related to a problem?
Yes, break duration cannot be set to seconds. 

## Describe the solution you'd like
Add support to set break duration to seconds. Maybe 10, 20, 40, 50 seconds would be okay.

## Describe alternatives you've considered
There is no alternative.

## Other information
There is a rule named as "20-20-20 Rule" to avoid eye strain. It says, "Set a timer to remind you to look away every 20 minutes at an object that is about 20 feet away for a full 20 seconds.". As the break duration cannot be set to 20 seconds, this rule cannot be followed.

**Comment by kamilprusko** [comment]
You can set duration in seconds using dconf editor or by commandline:
`$ gsettings set org.gnome.pomodoro.preferences short-break-duration 20.0`

The slider in the preferences dialog doesn't have resolution to allow seconds above 1 minute. It would be doable to include 30s or 20s / 40s. But still, I'm not in favor of breaking consistency.
