### ISSUE TITLE
possible missing dependency in meson.build

### ISSUE THREAD

**Issue by logrusx** [gnome-pomodoro/gnome-pomodoro#617]
## Issue Summary

Gnome pomodoro seems to be linked against cairo, but the dependency is missing from meson.build

## Steps to Reproduce

1. build gnome pomodoro
2. find plenty of references to cairo in the output

## Context (logs, error output, screencast, OS, Desktop  etc)

I'm maintaining a Gentoo ebuild and a qa tool identified possible issues with the ebuild:
```
qa-vdb gnome-pomodoro

VDB: detected possibly incorrect RDEPEND (gnome-extra/gnome-pomodoro-0.20.0)
dev-libs/gobject-introspection < 
x11-libs/gdk-pixbuf:2          < 
                               > x11-libs/cairo
```
While the author warns to take the dependencies considered redundant with a grain of salt because it's still not sure if the ebuild needs them at a certain point, the ones that are considered missing are identified by analysis of the binaries.

Since a dependency to cairo is missing from meson.build which is the main source of dependencies, could you please verify if there is indeed a dependency to cairo?

## Expected Behavior

All dependencies should be listed in meson.build

## Current Behavior

It only compiles because cairo is a very common component, but technically all dependencies should be listed

## Possible Solution

Add all dependencies to mesonbuild

## Other information

GNOME 41/Wayland running on Gentoo Linux
The ebuild with reflected missing dependency, although it may mean nothing outside of Gentoo Linux context, is located here: https://github.com/logrusx/gentoo/blob/master/logrusx/gnome-extra/gnome-pomodoro/gnome-pomodoro-0.20.0.ebuild

**Comment by kamilprusko** [comment]
Hi @logrusx 

Yes, gnome-pomodoro directly uses cairo. Added in 93f834d61fb253a28feabe1bf11d6bf62047501d.

Cairo is a dependecy of GTK3, that's why there were no issues so far.

**Comment by logrusx** [comment]
@kamilprusko thank you!
