### ISSUE TITLE
gnome-pomodoro-0.20.0 fails on Gnome 42

### ISSUE THREAD

**Issue by logrusx** [gnome-pomodoro/gnome-pomodoro#618]
## Issue Summary

I recently updated to Gnome 42 and modified the extension manually to support it.

## Steps to Reproduce

Modify metatdata.js to include compatibility with Gnome 42

## Context (logs, error output, screencast, OS, Desktop  etc)

The following appears in the logs:

gnome-shell-extension.vala:406: Extension error: Clutter.get_default_frame_rate is not a function

## Current Behavior

Topbar icon doesn't show up. Standalone application starts up but on exit it shows the same error.

**Comment by DimStar77** [comment]
Fixed in main branch already:

* https://github.com/gnome-pomodoro/gnome-pomodoro/commit/c008099ff773b798b8a682b4babcecaad6156e85
* https://github.com/gnome-pomodoro/gnome-pomodoro/commit/8322547e61fb32a68b76a84d0b9dd2702479c35d

**Comment by logrusx** [comment]
Thank you for letting me know, @DimStar77!
I just built from master and it's indeed fixed.
