### ISSUE TITLE
v0.21.0 automatically starts the next pomodoro session after breaks

### ISSUE THREAD

**Issue by unsungNovelty** [gnome-pomodoro/gnome-pomodoro#620]
## Issue Summary

Until v0.20.0. We have to manually start pomodoro sessions after break. With v0.21.0 it is automatically starts the next sessino after the break is over. I am not sure if this is a bug or a change since some pomodoro apps forces this behaviour. 

If it is a feature, I would like to say that it increases the error-rate of how much **we actually worked** by a huge proportion. It forces you to work too fast which is not ideal. If it is a feature, do have an option to enable and disable it please.

## Steps to Reproduce

1. Start a pomodoro session.
2. Finish the pomodoro session and enjoy your break 🍹 
3. And walk in a min later only to realise pomodoro session automatically started.

## Context (logs, error output, screencast, OS, Desktop  etc)

- Arch Linux
- i3 twm
- Version - v0.21.0 

## Expected Behavior

After a break is done, the app should wait for the user to start the next pomodoro session.

## Current Behavior

It automatically starts the next pomodoro session without the need for end user starting the pomodoro sessino.

## Possible Solution

N/A

## Other information

N/A

--- 

Thanks a lot for maintaining this. This has been in my life for [2-3 years](https://github.com/gnome-pomodoro/gnome-pomodoro/issues/469) now. Glad to know that you are working on a GTK4 port! Appreciate it. 🙇🏽‍♂️

**Comment by sojusnik** [comment]
For me this is clearly a bug. I totally love that after a break a Pomodoro only starts after user interaction.

**Comment by unsungNovelty** [comment]
@sojusnik . I have a feeling this has something to do with breaks being handled. So it is the expected behaviour to move to a break without the need for user's intervention. So maybe the desired behaviour post breaks got messed up too? I wonder if this bug was introduced during the recent v0.21.0 release.

**Comment by ethereal-engineer** [comment]
There used to be an option to wait for user interaction before starting the next pomodoro, but that seems to have vanished.

**Comment by sojusnik** [comment]
> There used to be an option to wait for user interaction before starting the next pomodoro, but that seems to have vanished.

It would be great, if it could be reimplemented, since it was very useful.

**Comment by ethereal-engineer** [comment]
As a workaround, until this is addressed, you could use the in-built "custom actions" plugin to tell gnome-pomodoro to stop itself at the conclusion of each break period.

![image](https://user-images.githubusercontent.com/2148403/168188365-8c363e42-8c4e-4aea-a8e5-b4586882d7fa.png)

**Comment by real-or-random** [comment]
@kamilprusko Was this a deliberate change?

**Comment by kamilprusko** [comment]
@real-or-random it wasn't a deliberate change - it's a regression. FWIW, it still works in GNOME 41.

**Comment by sojusnik** [comment]
> @real-or-random it wasn't a deliberate change - it's a regression. FWIW, it still works in GNOME 41.

Can we bring it in Gnome 42, because it's such a useful feature to have.

**Comment by kamilprusko** [comment]
@sojusnik I'll look into it in coming weeks. Unfortunately, I couldn't look into it sooner :(

**Comment by real-or-random** [comment]
> @sojusnik I'll look into it in coming weeks. Unfortunately, I couldn't look into it sooner :(

Thanks for all your work!

**Comment by unsungNovelty** [comment]
FWIW I moved to this workflow. IT'S NOT A BUG, IT'S A FEATURE!! 😄  
It pushes me to do stick to pomodoro sessions after short breaks. Thanks to the regression! :)

As @ethereal-engineer pointed out, you can use the custom actions plugin to make it automatically start after the break. Or the opposite way. To stop only after one complete (4 pomodoro sessions), use the below. I am guessing when this bug is fixed, I will have to change a little.

In case anybody is interested on how to stop only after long break:
![image](https://user-images.githubusercontent.com/11845908/177786552-1383a93e-7a09-4630-9a21-a8b33bfab9d2.png)

**Comment by real-or-random** [comment]
@kamilprusko If you have just 5 min, could you have a look at #610? It's literally a one-line change, so it should be a very quick review.
