### ISSUE TITLE
Polybar integration - showing status indicator

### ISSUE THREAD

**Issue by Jdude311** [gnome-pomodoro/gnome-pomodoro#621]
## Is your proposal related to a problem?

There is currently no way to get the timer's status using the command line, which means that the application cannot be integrated into systems other than GNOME (I was trying to write a polybar module for myself that would display the timer).

## Describe the solution you'd like

Add a command line switch that would allow users to get the timer status as follows:
`gnome-pomodoro --status`

## Describe alternatives you've considered

Writing it myself into the source code. It makes more sense to submit a pull request, though, so others can use the feature.

## Other information

I might be able to implement this myself over the next few days but I'm not sure as my time is currently limited due to upcoming AP testing.

**Comment by kamilprusko** [comment]
Hi @Jdude311 

The recommended way would be to use d-bus:
- less overhead
- you could attach signals on changes, no need to periodically call a command

I see that there are status indicators based on DBus
https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/player-mpris-tail

**Comment by kamilprusko** [comment]
I recommend playing with D-Feet to explore DBus interface 
![Screenshot from 2022-04-26 10-43-26](https://user-images.githubusercontent.com/1135423/165260179-07572da2-fc14-48b4-9fd3-db124e8f3112.png)

**Comment by Jdude311** [comment]
Thank you! I will be taking a look at that.

**Comment by JakeGinesin** [comment]
for those finding this thread now and looking to implement this into your own polybar setup, follow these steps. 

First, a non D-Feet solution for exploring the dbus interface hooks is `qdbus`. List the paths of the interfaces as such:
```
$ qdbus org.gnome.Pomodoro                                                                                         
/
/org
/org/gtk
/org/gtk/Profiler
/org/gnome
/org/gnome/Pomodoro
/org/gnome/Pomodoro/window
/org/gnome/Pomodoro/window/1
```
Then, add the correct directory for your system:
```ba
$ qdbus org.gnome.Pomodoro /org/gnome/Pomodoro
... 
property read double org.gnome.Pomodoro.Elapsed
property read bool org.gnome.Pomodoro.IsPaused
property read QString org.gnome.Pomodoro.State
property read double org.gnome.Pomodoro.StateDuration
property read QString org.gnome.Pomodoro.Version
...
```

using the above hooks, I wrote the following python script to fetch the current time and status of the gnome pomodoro app. It requires the `gi` package, so make sure to install that. 

```
import gi
import time
gi.require_version('Gio', '2.0')
from gi.repository import Gio, GLib

class PomodoroInterface:
    def __init__(self):
        # Initialize the DBus interface
        self.bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
        self.dbus_proxy = Gio.DBusProxy.new_sync(self.bus, Gio.DBusProxyFlags.NONE, None,
                                            'org.freedesktop.DBus', '/org/freedesktop/DBus', 'org.freedesktop.DBus', None)

        # Check if Pomodoro is active
        active_services = self.dbus_proxy.ListNames()
        if 'org.gnome.Pomodoro' not in active_services:
            #print("Pomodoro is not active.")
            exit(0)

        self.proxy = Gio.DBusProxy.new_sync(self.bus, Gio.DBusProxyFlags.NONE, None,
                                            'org.gnome.Pomodoro', '/org/gnome/Pomodoro', 'org.gnome.Pomodoro', None)

    def get_remaining_time(self):
        # Get the current state and remaining time
        state = self.proxy.get_cached_property('State').unpack()
        if (state == "null"):
            print("")
            exit(0)

        elapsed = self.proxy.get_cached_property('Elapsed').unpack()
        state_duration = self.proxy.get_cached_property('StateDuration').unpack()
        remaining = state_duration - elapsed

        # Format the remaining time as minutes:seconds
        minutes = int(remaining) // 60
        seconds = int(remaining) % 60
        formatted_remaining = f"{minutes}:{seconds:02d}"
        if (state == "short-break"):
            state="break"

        print(f"{state} - {formatted_remaining}")

if __name__ == "__main__":
    pomodoro = PomodoroInterface()
    pomodoro.get_remaining_time()
```

And here's what I have for my polybar module:
```
[module/pomodoro]
type = custom/script
tail = true
format = <label>
exec = "python3 /path/to/script/script.py 2> /dev/null"
```

The end result looks like this:
![image](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/39607713/4d16198a-48b7-44ea-aa7f-f1c6d2339e48)

hope this helps o7
