### ISSUE TITLE
Screen overlay does not show seconds

### ISSUE THREAD

**Issue by TriplEight** [gnome-pomodoro/gnome-pomodoro#627]
## Issue Summary

Describe your issue here.

## Steps to Reproduce

1. run the program
  ```bash
  $ gnome-pomodoro

  (gnome-pomodoro:194462): libpeas-WARNING **: 17:31:15.413: Failed to load module 'notifications': /usr/lib/gnome-pomodoro/plugins/libnotifications.so: cannot open shared object file: No such file or directory

  (gnome-pomodoro:194462): libpeas-WARNING **: 17:31:15.413: Error loading plugin 'notifications'
  ```
2. Have screen notifications turned on in preferences
3. Pick a short or long break or wait until it starts
4. Splash screen shows i.e.

##             5:...

Doesn't show seconds.

## Context (logs, error output, screencast, OS, Desktop  etc)

Arch Linux

## Expected Behavior

It's shown seconds the firs time after I've installed it

## Current Behavior

And now it doesn't

## Possible Solution

Seems it's plugin missing

## Other information

(Write your answer here.)

**Comment by kamilprusko** [comment]
Fixed in master branch.

It was occurring with certain fonts.
