### ISSUE TITLE
Force final 10s pop up notification even when firefox is full-screened

### ISSUE THREAD

**Issue by Keyikedalube** [gnome-pomodoro/gnome-pomodoro#628]
## Issue Summary

When I am fully focused on reading my emails or watching videos I tend to always fullscreen my Firefox window. The problem is I don't get the final 10s countdown remaining notification with my browser full-screened. Pomodoro taking over without warning disrupts my workflow because I like to be prepared by marking where I left off or pausing the video so it doesn't continue playing in the background while the break is ongoing. 

## Steps to Reproduce

1. Launch Firefox
2. Fullscreen browser window (F11)
3. Wait for Pomdoro to take over without notification pop up

## Context (logs, error output, screencast, OS, Desktop  etc)

_None_

## Expected Behavior

Show notification even when full-screened

## Current Behavior

Shows notification if browser is windowed/maximized but not full-screened

## Possible Solution

Force notification even if browser is full-screened

## Other information

I suspect my low 4GB RAM is to blame. Memory swapping could've probably caused that missed notification.

**Comment by kamilprusko** [comment]
Fixed this in [wip/notification-manager](https://github.com/gnome-pomodoro/gnome-pomodoro/tree/wip/notification-manager) branch. I expect to merge it in a week or two, if there are no issues.

**Comment by kamilprusko** [comment]
It's fixed in master branch.
