### ISSUE TITLE
Circular timer indicator is very thin on HiDPI displays

### ISSUE THREAD

**Issue by SamuelBorn** [gnome-pomodoro/gnome-pomodoro#636]
## Issue Summary

The circular line which makes the timer in the tray has, _I assume_, a fixed width.
That's why the circle looks much too thin on devices with high DPI.

## Steps to Reproduce

1. Install gnome-pomodoro on machine with HiDPI display
2. Enable the timer in extensions manager
3. See the circle

## Possible Solution

Make the circle width dependent on the screen-resolution-

**Comment by kamilprusko** [comment]
Fixed in [0.22.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.22.0)
