### ISSUE TITLE
Shell crashes when exiting fullscreen overlay 

### ISSUE THREAD

**Issue by real-or-random** [gnome-pomodoro/gnome-pomodoro#640]
## Issue Summary

GNOME Shell crashes with
```
Nov 21 13:04:00 gnome-shell[88517]: libmutter:ERROR:../mutter-performance/src/compositor/meta-surface-actor-wayland.c:113:meta_surface_actor_wayland_is_stage_view_current_primary_view: assertion failed: (l->data == stage_view)
Nov 21 13:04:00 gnome-shell[88517]: Bail out! libmutter:ERROR:../mutter-performance/src/compositor/meta-surface-actor-wayland.c:113:meta_surface_actor_wayland_is_stage_view_current_primary_view: assertion failed: (l->data == stage_view)
Nov 21 13:04:00 gnome-shell[88517]: == Stack trace for context 0x556aee25b7d0 ==
```
(and then no stack trace follows)

## Steps to Reproduce

This seems to happen whenever the extension tries to exit the fullscreen overlay.

Disabling the shell extension makes the issue disappear.

## Context (logs, error output, screencast, OS, Desktop  etc)

on Wayland, GNOME Shell 43.1, Arch Linux

edit: Oh, I just remembered that I'm running a patched mutter. Let me first try with the original mutter first... I'll update this.

**Comment by kamilprusko** [comment]
Thanks for reporting the issue. I'll look into it.

At first glance it looks like low-level issue. Indeed could be libmutter.

**Comment by real-or-random** [comment]
Okay, apparent happens only with a patched mutter, see my comment here: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2671#note_1599943

But maybe let's keep this open for now until we've figured out whether mutter or gnome-pomodoro is to blame.

**Comment by FiestaLake** [comment]
@real-or-random You should try to add a debug option in mutter-performance's PKGBUILD file and get the proper stack trace with something like gdb. The option is disabled by default for possibly increased performance and decreased package size. This can happen due to the backend side's behavior change of that MR.

**Comment by real-or-random** [comment]
I'm happy to do that if asked by the mutter maintainers in their upstream, because then I know this is well-invested time.

**Comment by kamilprusko** [comment]
Made a change 16db887 to destroy `Clutter.Clone` instead of hiding it. Seems to fix this issue.
