### ISSUE TITLE
I can't escape the break interval window notification

### ISSUE THREAD

**Issue by trolliama** [gnome-pomodoro/gnome-pomodoro#641]
## Summary

My issue is related to the block that the extension makes on my computer every time a break starts. I like this feature of blocking my window with this blur effect and the timer but sometimes I would like to get out of this just for a moment to finish something and then get back to it. Normaly I disable this break "window" pressing `esc` and sometimes does work but almost never does.

## Steps to Reproduce

1. Wait for the break time
2. Keep moving your mouse when the notification of finishing the pomodoro time appears
3. You probably wont be able to remove the blurred window

## Context (logs, error output, screencast, OS, Desktop  etc)
OS: Ubuntu 22.04
Pomodoro exetension version inside the metada.json is 0.22.1

## Other information

Obs: What I noticed (I can be wrong) is that every time the mouse is not moving and this breaks starts I am able of escaping it, otherwise I am not.

**Comment by trolliama** [comment]
I didn't manage fixing it but every time this happens I use the shortcut `alt+ctrl+p` to stop the timer

**Comment by kamilprusko** [comment]
> pressing esc and sometimes does work but almost never does.

Fixed that in master branch

Closing, as it's same issue as #635

**Comment by trolliama** [comment]
Okay I have updated to the master version and it din't fixed. Beside that I also noticed a problem at my left corner, my mouse isn't clickable there, like some window was in front of everything and I am not able to click the firefox tabs for example.

![image](https://user-images.githubusercontent.com/21108976/210380323-05ee8077-5eff-4460-a5d3-4fd4b5737472.png)
The area inside the red rectangle isn't clickable on any of my programs. 

I don't know if I have uninstalled incorrectly and then installed the master version or if it really has a bug. The way I uninstalled it was deleting the pomodoro gnome extension folder. After that I just followed the site steps for the installation via github link (but I have used the master branch)

**Comment by kamilprusko** [comment]
@trolliama Thank you for feedback!

Do you see anything related in logs?
```
$ journalctl --user --identifier=gnome-shell --since "1 day ago"
```

I'll try to test this on GNOME 40, as on Ubuntu 22.04

**Comment by trolliama** [comment]
Nothing related from what I see. 

A quick update is that the problem with the blurred window was actually solved (in part). I just needed to turn off the extension and turn it on again. The thing now is that when I move my mouse the blurred window disappear (like when I press the esc key). It's way better than lock my whole window as it was doing before so as I don't know if it's an intentional feature or a bug here is my observation

**Comment by trolliama** [comment]
Also one more thing is that when I deactivate the extension:

![image](https://user-images.githubusercontent.com/21108976/210441215-1290a510-772f-4678-a64b-f992dfb024ee.png)

It continues working and only hide the indicator from task bar

**Comment by kamilprusko** [comment]
> I also noticed a problem at my left corner, my mouse isn't clickable there, like some window was in front of everything and I am not able to click the firefox tabs for example.

Fixed in master branch.

> It continues working and only hide the indicator from task bar

It comes with an app, the app continues to run in background... You can use "Quit" from the indicator menu to shut it down completely.

**Comment by trolliama** [comment]
It's working now. Thanks!!
