### ISSUE TITLE
Expose app actions without extension

### ISSUE THREAD

**Issue by kalinchernev** [gnome-pomodoro/gnome-pomodoro#650]
## Is your proposal related to a problem?

I'm on Gnome Manjaro and gnome-pomodoro is provided to me as one of the default apps comingp pre-installed. It was last week when an update in something happened and I can't use gnome-pomodoro any more. 

The big problem I'm facing as a user is that the extension integrating gnome-pomodoro with the gnome shell can no longer be enabled. When enabled, the session gets killed and I'm logged out. I can still run the app, but it's not usable without the extension.

Although I haven't had the time to pinpoint the exact problem with the extension (gjs suspected) I'll be happy enough to go without the extension and only with the app. However, the app by itself (without the extension) does not provide a navigation: no way to start a break, only start/stop a pomodoro.

## Describe the solution you'd like

If it would be possible to include app actions (start/stop + break/pomodoro) from the app itself so that it can be used without the extension.

## Describe alternatives you've considered

I've considered using other apps, but they are either over-complicated or not as neatly integrated into gnome shell as gnome-pomodoro.

## Other information

(Write your answer here.)

**Comment by kamilprusko** [comment]
Hi @kalinchernev

Thank you for your feedback. The crash has been reported here: https://github.com/gnome-pomodoro/gnome-pomodoro/issues/646

Currently you can start Short Break / Long Break manually:
![Screenshot from 2023-03-08 10-21-24](https://user-images.githubusercontent.com/1135423/223673841-790b2665-b1c2-4aea-96c7-fb63b3622e36.png)

In upcoming release (for GNOME 44) there will be a skip button, as in the screenshot.

**Comment by kalinchernev** [comment]
Oh, thanks! I haven't really paid attention to this as it's not a button or an element that seems clickable.
But solves it for me for now, really thanks!
