### ISSUE TITLE
org.gnome.Pomodoro.appdata.xml installed as org.gnome.Pomodoro.appdata

### ISSUE THREAD

**Issue by jubalh** [gnome-pomodoro/gnome-pomodoro#651]
## Issue Summary

It seems like [0.23.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.23.0) installs org.gnome.Pomodoro.appdata instead of org.gnome.Pomodoro.appdata.xml.

## Steps to Reproduce

build

## Context (logs, error output, screencast, OS, Desktop  etc)

See https://build.opensuse.org/request/show/1074576

**Comment by kamilprusko** [comment]
I'm working on it...

**Comment by kamilprusko** [comment]
Fixed in e919584b584b8f407540d353e754a7b382ee2179

I've tagged new release [0.23.1](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.23.1)
