### ISSUE TITLE
On Gnome44 this shell extension not support

### ISSUE THREAD

**Issue by qwert-f** [gnome-pomodoro/gnome-pomodoro#653]
hope in a nearly future can support

**Comment by kamilprusko** [comment]
Version [0.23.x](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.23.1) do support GNOME Shell 44.

**Comment by kamilprusko** [comment]
0.22.x will work ok with newer GNOME Shell. As a quick workaround, you can bypass version validation:

```gsettings set org.gnome.shell disable-extension-version-validation true```
