### ISSUE TITLE
Wrong arrangement dialog from gnome tray icon

### ISSUE THREAD

**Issue by bigkrp** [gnome-pomodoro/gnome-pomodoro#664]
## Issue Summary

Wrong arrangement dialog from gnome tray icon

## Steps to Reproduce

1. Click on pomodoro icon from gnome tray

## Context (logs, error output, screencast, OS, Desktop  etc)
Fedora 38, Gnome 44.3, Wayland
![Screenshot from 2023-07-20 12-58-24](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/11586744/488c6376-fd6b-476c-8771-d596dcfc821d)
![Screenshot from 2023-07-20 12-58-15](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/11586744/299e88a2-8055-48a2-b41b-29c49839133e)
[Screencast from 2023-07-20 13-05-32.webm](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/11586744/254b5b5a-9459-4ac7-88c9-5d259ead4a81)

## Expected Behavior
Dialog is centered according to tray's pomodoro icon

## Current Behavior
Dialog arrangement to right according to tray's pomodoro icon, and it prevents to lose it, when trying move cursor down.

## Possible Solution
Cente dialog according to tray's pomodoro icon

**Comment by kamilprusko** [comment]
Thanks for reporting the issue :pray: 

It's now fixed in master / gnome-44 and gnome-45 branches. Will be included in release for gnome-shell 45.
