### ISSUE TITLE
command line to modify pomodoro, break and long break duration

### ISSUE THREAD

**Issue by Pavaningithub** [gnome-pomodoro/gnome-pomodoro#669]
## Is your proposal related to a problem?
I'm unable to modify pomodoro, break and long break duration using command line

(Write your answer here.)

## Describe the solution you'd like

I should be able to tweak timer. 
something like this `gnome-pomodoro --preferences --pomodoro 25 --break 5 --long-break 20`

or 
`gnome-pomodoro --start --pomodoro 25` which allows to customize pomodoro timer dynamically.

(Describe your proposed solution here.)

## Describe alternatives you've considered

(Write your answer here.)

## Other information

(Write your answer here.)

**Comment by kamilprusko** [comment]
Currently you could do it using `gsettings` command:
```
gsettings set org.gnome.pomodoro.preferences pomodoro-duration 1500.0
gsettings set org.gnome.pomodoro.preferences long-break-duration 900.0
gsettings set org.gnome.pomodoro.preferences short-break-duration 360.0
```

or by using D-Bus:
```
dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.SetState string:"pomodoro"
dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.SetStateDuration string:"pomodoro" double:"120.0"
```
First command switches to pomodoro. The second modifies duration, only if the state is still pomodoro.
