### ISSUE TITLE
[Feature Request] Display Remaining Time in Top Bar

### ISSUE THREAD

**Issue by jaemin-gurumnet** [gnome-pomodoro/gnome-pomodoro#672]
## Is your proposal related to a problem?

No

## Describe the solution you'd like

I would like to propose the addition of a feature that allows displaying the remaining time of the Pomodoro timer in the top bar of GNOME Shell Pomodoro. This feature would enhance the user experience by providing a quick and convenient way to monitor the progress of a Pomodoro session without opening the Pomodoro popup.

## Describe alternatives you've considered

I have considered the following alternatives:

1. Manually opening the Pomodoro popup to check the remaining time.
2. Using other Pomodoro timer apps that already offer this feature.

However, these alternatives are less convenient and may disrupt the workflow, especially for users who prefer to have a constant visual reminder of the remaining time on the top bar.

## Other information

Adding this feature could make GNOME Shell Pomodoro even more user-friendly and appealing to users who follow the Pomodoro technique for time management. It would also align the app with other Pomodoro timer tools that offer similar functionality.

Thank you for considering this enhancement to GNOME Shell Pomodoro.

**Comment by kamilprusko** [comment]
Do you mean you would like text instead of an circle progress-bar?

If so, there is an hidden setting for this:
```
$ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type text
$ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type short-text
$ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type icon
```

In future, I would like to add option to change the indicator type under "Appearance" section in the preferences window.

**Comment by jaemin-gurumnet** [comment]
Thanks for the quick reply, I will try to use that feature.
