### ISSUE TITLE
Tray icon stopped working with Gnome 45.1

### ISSUE THREAD

**Issue by bigkrp** [gnome-pomodoro/gnome-pomodoro#678]
## Issue Summary

The tray icon on the top bar disappeared.

## Steps to Reproduce

1. Update Gnome to 45.1

## Context (logs, error output, screencast, OS, Desktop  etc)

Fedora Linux 39 (Workstation Edition)

## Expected Behavior

I can use the tray icon on the top bar.

## Current Behavior

The tray icon on the top bar disappeared.

## Possible Solution

Update Gnome extention

**Comment by kamilprusko** [comment]
Hi, thanks for reporting the issue.

Fedora 39 ships now gnome-pomodoro 0.24, which is compatible with GNOME Shell 45. Please check whether the extension is enabled using the Extensions app.

**Comment by bigkrp** [comment]
I've just updated the Pomodoro, from `Software` and it works like a charm
