### ISSUE TITLE
Add a way to see how many rounds of pomorodoros we've done.

### ISSUE THREAD

**Issue by Phil305** [gnome-pomodoro/gnome-pomodoro#696]
## Is your proposal related to a problem?

No

## Describe the solution you'd like

It would be nice to have a way to see what round of our pomodoros we're on, similar to the attached image.
This could show how close we are to a long break.
It would also be nice if we could manually set ourselves to another round (e.g. go from the last round before a long break to the 2nd round) by clicking one of the icons indicating which round we're on.
![Screenshot from 2024-03-31 17-15-38](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/19247724/684aad7f-54d1-4098-9682-c44189938b67)

## Describe alternatives you've considered

The app could just show a number indicating which round we're on, instead of icons. Then, we could click the number and manually change which round we're on

**Comment by kamilprusko** [comment]
In wip/gtk4 branch it shows the number of cycles/rounds in the app. Not sold on the idea of choosing the current cycle manually - to me adding/removing cycles would be more intuitive (not available yet). The number of cycles adjusts to usage: skipping the long break adds a cycle; extending the pomodoro can make the dash appear longer; forcing and completing a long break resets the session indicator.

![Screenshot from 2024-03-31 23-22-54](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/1135423/ab405217-8891-4349-b059-8871ca2f2f77)

Closing, as there is a similar issue reported https://github.com/gnome-pomodoro/gnome-pomodoro/issues/524

**Comment by Phil305** [comment]
@kamilprusko wonderful, this is perfect, thanks for the info!

Quick question; if I install from source, do you know if I will still be able to have the app pop up in my top menu bar (Gnome 45.5 on Wayland; Fedora 39).

![Screenshot from 2024-04-01 09-46-03](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/19247724/726347ef-4ac9-4c0d-8b6a-87d40b75a19f)

**Comment by kamilprusko** [comment]
>  if I will still be able to have the app pop up in my top menu bar

Yes, installing app from source will install the GNOME Shell extension. It may not get recognised at first, so a logout is advised.
