### ISSUE TITLE
Fedora 40 - Compilation requires libpeas1-devel

### ISSUE THREAD

**Issue by felixschurk** [gnome-pomodoro/gnome-pomodoro#698]
## Issue Summary

Following the description on the website and copy the install dependencies is missing the `libpeas1-devel` package which is then unable to compile. 

## Steps to Reproduce

1. Follow build instructions on Fedora 40 from the website

## Context (logs, error output, screencast, OS, Desktop  etc)
```sh
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libpeas-1.0 found: NO (tried pkgconfig and cmake)

meson.build:18:11: ERROR: Dependency "libpeas-1.0" not found, tried pkgconfig and cmake
```

## Expected Behavior
Compiling should be possible.

## Current Behavior
Missing the `libepeas1-devel` library

## Possible Solution
```sh
sudo dnf install libpeas1-devel
```
Then it is able to compile.

## Other information
Probably then the `libpeas-devel` is no longer needed.

**Comment by kamilprusko** [comment]
Thanks for reporting the issue.

I've updated the instructions. In Fedora 39+ the package is named `libpeas1-devel`, previously it was named `libpeas-devel`.
