### ISSUE TITLE
Top bar icon not shown in Gnome 46

### ISSUE THREAD

**Issue by kchousos** [gnome-pomodoro/gnome-pomodoro#699]
## Issue Summary

The program itself runs fine, but the extension side of it, meaning the top bar icon with the quick preferences, doesn't work. Extension manager shows the following error:

```
TypeError: class heritage MessageTray.NotificationBanner is not an object or null
```

## Other information

Running Fedora 40.

**Comment by kamilprusko** [comment]
You don't have the newest release...

GNOME Shell 46 is supported by [0.25.1](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.25.1). Package for Fedora 40 is in testing https://packages.fedoraproject.org/pkgs/gnome-pomodoro/gnome-pomodoro/ . I believe it should be available soon.
