### ISSUE TITLE
Notification hides very fast after pressing +1 minute button in it.

### ISSUE THREAD

**Issue by logrusx** [gnome-pomodoro/gnome-pomodoro#702]
## Issue Summary

When a notification that pomodoro ends appear, it would allow me to extend the pomodoro with only 1 minute and only if I press the button with a specific delay I can get it to 2 minutes, but not more. I suspect this is because the program logic hides the notification as soon as the time remaining becomes bigger than the threshold that triggers the notification.

## Steps to Reproduce

1. Start a pomodoro (for faster results set the pomodoro duration to 1 minute);
2. Wait till the notification appears;
3. Try to press the +1 minute button several times. At best you'll get it to 2 minutes extension.

## Context (logs, error output, screencast, OS, Desktop  etc)

Gnome Pomodoro 0.25.0;
Gnome 45.5 running on Wayland or Xorg;
Gentoo Linux.

## Expected Behavior

The notification should persist for as long as the mouse is hovering it.

## Current Behavior

The notification hides as soon as the program logic detects the remaining time is bigger than the threshold that activates it, perhaps with a small additional delay which allows me to sometimes get a second click on the +1 minute button.

## Possible Solution

Add logic to keep the notification until the mouse moves off of it.

## Other information

I believe this behavior has been present ever since Gnome Pomodoro moved off of Ayatana Indicators but can't confirm it.

**Comment by kamilprusko** [comment]
I'm working on a patch for GNOME 46...

**Comment by kamilprusko** [comment]
Pushed a fix to master and gnome-46 branches. If I find no issues by Friday, I'll tag the release.

Investigating the issue on GNOME Shell 45...

**Comment by logrusx** [comment]
> Investigating the issue on GNOME Shell 45...

Thank you very much! I would very much appreciate that as Gnome 46 still hasn't found its way into Gentoo, even as testing version.

**Comment by kamilprusko** [comment]
Fix released in versions:
- [0.25.2](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.25.2) for GNOME Shell 46
- [0.24.2](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.24.2) for GNOME Shell 45

Patch for both is mostly the same - it allows having different behaviour (urgency), regardless of displayed content. It introduces another issue on GNOME Shell 45 though. A notification is missing after extending pomodoro and skipping it. But, as this is not a normal flow, I'll let it pass... in 46 it works ok.
