### ISSUE TITLE
Conflict 'Escape' Key with org.gnome.mutter locate-pointer-key

### ISSUE THREAD

**Issue by yashi** [gnome-pomodoro/gnome-pomodoro#707]
## Issue Summary

I use "Locate Pointer" feature of GNOME Shell, which is under "Accessibility", with non-default key, `Escape`.  The default key is `Control_L`.

```
❯ gsettings get org.gnome.mutter locate-pointer-key
'Escape'
```

With this seeting, when pomodoro timer expiers, or do `gnome-pomodoro --skip`, and enters a short break, I can't get out the break even if I hit Escape key.

This remains even if I disabled "Locate Pointer" feature.

## Steps to Reproduce

1. `gsettings set org.gnome.desktop.interface locate-pointer false` # Make sure it's not active
2. `gsettings set org.gnome.mutter locate-pointer-key Escape` # Set Escape for the accelerator
3. `gnome-pomodoro --skip` # to enter short break (or just wait)

## Expected behavior

Exit from break screen even with the above setting.

## Current behavior

You can't exit from the break screen.

## Workaround

Hit `Ctrl` + `Alt` + `P`, to disable Pomodoro.

### Logs

I see the following warning in the journal:

```
gnome-shell[2478]: Pomodoro: Failed to grab accelerator for the dialog.
```

### OS Information

- OS: Debian Sid
- GNOME Shell: 44.9-2+b1
- Mutter: 44.8-3.1+b3
- Pomodoro: 0.23.1-1+b3

### Looking Glass

In the GNOME shell looking glass, I did:

```
global.display.grab_accelerator("Escape", 0)
```

And indeed I get `0` when `Escape` is set to the `locate-pointer-key`, and get `316` when not.

**Comment by kamilprusko** [comment]
Hi @yashi , Thank you for a detailed report

I can confirm that I'm not able to dismiss the overlay by Escape key, but only if there is a video playing in the background - without a video playing I'm still able to dismiss it. After pausing playback I can dismiss the overlay normally.

Prepared a fix 78cb8315adb6955dcc7da90705a89fe377e36b25 in gnome-45 branch, and I removed the fallback method for dismissing overlay by Escape key, so there won't be collisions with other accelerators.

**Comment by yashi** [comment]
Hi @kamilprusko 

Indeed. I was playing music (YouTube Music on Chrome App) when I tested. And I can confirm that without playing music, I can dismiss the overlay, even with `Escape` key set to `locate-pointer-key`. Apologize for a confused bug report.

And thanks for the fix.  Unfortunately, Debian is still stack with GNOME Shell 44. So I'm unable to test it right now.

**Comment by kamilprusko** [comment]
I've adjusted patches for [gnome-44 branch](https://github.com/gnome-pomodoro/gnome-pomodoro/tree/gnome-44) but without testing. I no longer have environment for GNOME 44...

I'll need more time testing it on GNOME 46, as I can't reproduce the issue in jhbuild / nested GNOME Shell. I need to upgrade my OS.

**Comment by yashi** [comment]
Just tested the `gnome-44` branch by

```
rm -rf builddir && meson setup builddir && ninja -C builddir
cd plugins/gnome/extension/
sudo cp indicator.js dialogs.js /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/
```

(I know it's not a proper way to test it but it seems the only change I have with the `gnome-44` branch against the debian packages, `gnome-shell-pomodoro` and `gnome-shell-pomodoro-data`, are these these two files.)

The fix seems change how to dismiss the overlay.  With the changes, I can dismiss it by moving mouse, click it, or hit any key on my keyboard _as soon as the overlay is activated_.  This wasn't the case without the fix.

I'm not sure how it works but let me explain.  I usually working with gnome-terminal.  And I just tested with it bcause I need to `gnome-pomodoro --skip` to get the overlay.

- **Without fix**: I have to wait a few second to change my mouse cursor from the `I` shape to the arrow shape in the overlay to make `Escape` key or any dismissing action
- **With fix**: My mouse cursor change from the `I` shape to the arrow shape as soon as the overlay is activated.

BTW, This is without running YouTube Music on the Chrome app. Or any other app for that matter.

**Without**
[Screencast from 2024-06-28 06-12-57.webm](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/10152/7ee43496-3854-4e82-a7d7-3e0af37063f0)
**With**
[Screencast from 2024-06-28 06-12-57.webm](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/10152/ac1d3ccc-0e22-4334-b7b5-46826a57970e)

If that's what the change means, it's working for me on Debian Sid with GNOME Shell 44.

Hope this helps.

**Comment by kamilprusko** [comment]
The change of the behaviour wasn't intended... Thanks @yashi for spotting this!

The patch detects if there's a video playing. One of the method video players use is setting IDLE inhibitor flag in session manager to prevent activating the screen saver. If such flag is set then we steal focus earlier, not relying on built-in IdleMonitor. Somehow, dismissing the overlay became easier even if video is not playing.

I think it can be improved. To grab focus earlier than previously, but not to be too greedy as in the initial patch... This will require refactoring, and I won't feel comfortable back-porting it to GNOME 44.

**Comment by yashi** [comment]
> I won't feel comfortable back-porting it to GNOME 44.

I understand. Don't waste your time supporting old ones. You have already done more than enough.  Thank you for your kind support, @kamilprusko! I'm closing this.
