### ISSUE TITLE
Notifications appear even when notifications are switched off

### ISSUE THREAD

**Issue by mohemiv** [gnome-pomodoro/gnome-pomodoro#710]
Notifications are appearing even when the notification settings are disabled. This issue affects the user experience as it contradicts the user's settings preferences.

![Screenshot from 2024-06-27 18-49-34](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/5724896/7dd077fc-194e-4579-806e-c193804e0457)

![Screenshot from 2024-06-27 18-49-45](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/5724896/bc693ecf-d6d5-4db4-bb73-7ae88528b0c3)

**Comment by kamilprusko** [comment]
"Screen notifications" refers to the screen overlay during break.

In wip/gtk4 branch I hope it's clearer

![Screenshot from 2024-06-27 20-01-24](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/1135423/af36baa5-77ef-4c65-ae22-f4e36938ce1b)
