### ISSUE TITLE
Timer is double-counting time spent doing intervals

### ISSUE THREAD

**Issue by pmer** [gnome-pomodoro/gnome-pomodoro#716]
## Issue Summary

Sometimes, GNOME Pomodoro counts more time spent per day than there are hours in the day.

## Steps to Reproduce

1. Not sure.

## Context (logs, error output, screencast, OS, Desktop  etc)

Version: 0.25.1
OS: Ubuntu 24.04

![image](https://github.com/user-attachments/assets/fcc5dee5-e6c7-4a17-9b72-67087c9f9f6b)

## Expected Behavior

Timer should claim I spent 16 hours doing intervals, or something like that.

## Current Behavior

Timer claims I spent 32 hours doing intervals.

**Comment by kamilprusko** [comment]
Thanks for reporting this.

I may need more time to find a way to reproduce it... Currently there is no validation in `Application.on_timer_state_changed` ensuring there's no overlap - it assumes we cleanly transition between a `break` and `pomodoro`. So, that one potential fix.

I'm currently rewriting stats for the wip/gtk4 branch from the ground up. For sure this will be addressed properly there.

**Comment by pmer** [comment]
Thanks for the info! I'll keep playing around and if I run into any ideas about the underlying cause of this bug I'll report it here.

**Comment by pmer** [comment]
I have another hypothesis about the source of this issue. Instead of time being double-counted, as the title of this issue posits, maybe time is counted even when the system is suspended/sleeping.

Can try this set of production steps:

1. Start a pomodoro.
2. Suspend/sleep the system.
3. Come back over 24 hours later.
4. Go to the "stats" page & observe how much time was spend during pomodoros. Maybe it will say over 24 hours in one day.

**Comment by pmer** [comment]
Hi, another update. I can confirm that time is counted even when the computer is suspended. Last night I was in the middle of a pomodoro break, and when I came back in the morning, it said I had spent the hours from midnight to 9 AM taking 9 hours of breaks.

![image](https://github.com/user-attachments/assets/cb234532-8015-43c3-9bac-49eeb317cb91)

**Comment by pmer** [comment]
Interestingly, I do get some results for that SQL query:

```
2024-09-15T06:25:54+0000|short-break|15|2024-09-15T06:25:54+0000|long-break|27
2024-09-15T06:25:54+0000|short-break|15|2024-09-15T06:25:54+0000|short-break|300
2024-09-15T06:25:54+0000|long-break|27|2024-09-15T06:25:54+0000|short-break|15
2024-09-15T06:25:54+0000|long-break|27|2024-09-15T06:25:54+0000|short-break|300
2024-09-15T06:25:54+0000|short-break|300|2024-09-15T06:25:54+0000|short-break|15
2024-09-15T06:25:54+0000|short-break|300|2024-09-15T06:25:54+0000|long-break|27
2024-09-23T21:27:41+0000|short-break|79|2024-09-23T21:27:51+0000|pomodoro|1500
2024-09-26T18:36:40+0000|short-break|925|2024-09-26T18:49:33+0000|pomodoro|1500
2024-09-26T19:46:45+0000|long-break|900|2024-09-26T19:59:40+0000|pomodoro|1500
2024-10-08T22:02:18+0000|long-break|900|2024-10-08T22:06:10+0000|pomodoro|1500
2024-10-10T23:48:35+0000|long-break|471|2024-10-10T23:54:54+0000|pomodoro|3971
2024-10-23T21:03:41+0000|long-break|308|2024-10-23T21:03:47+0000|pomodoro|0
```

**Comment by pmer** [comment]
> If the timer is running when rebooting or suspending, the time is still counted. This behaviour needs to change... Looking into it.

I'd be super interested in helping out... although I'm not sure if I have the free time for it right now. Maybe in a week or two when things settle down at work. I've actually been thinking about one idea that could be done for this: We could have a timer go off every minute, and if more than two minutes (or something a tiny bit bigger than 1 minute, basically) have elapsed since the timer was started, we cap it.

> The reason why it displayed "31h" is because it doesn't cap the time to midnight. It could be fixed by splitting an entry at midnight, but in my opinion it's better to fix it while implementing a virtual midnight.

Interesting. If you don't my curiosity, what would a virtual midnight be?

**Comment by kamilprusko** [comment]
Thank you for providing query results. There are indeed overlaps. Possibly when skipping a break, not sure.

A virtual midnight could be set to 2AM. The idea is that the daily stats would then show activity between bedtimes.

> We could have a timer go off every minute, and if more than two minutes (or something a tiny bit bigger than 1 minute, basically) have elapsed since the timer was started, we cap it.

Other solution could be splitting an entry at midnight into two entries in Vala.

I'd like to focus on gtk4 version for the coming week. Think how it should be done properly. Mockup:

![g63168](https://github.com/user-attachments/assets/5c87ff80-e0c9-4d5b-878f-161a167b66d5)

**Comment by kamilprusko** [comment]
Made few changes:
- database entries for the stats are split at midnight (e48768933644c0f7b6a35895356d230b6f6e926b)
- when suspending the system, it will stop the timer after one hour (9f1a61d2838aec0a6ce498fe4009f0837bea70dd)
- below one hour and 10 seconds it will treat elapsed time as a pause

It's quick and dirty patch. Still needs more testing. I'll do it properly in wip/gtk4 branch.
