### ISSUE TITLE
Tray icon unavailable in Gnome 46

### ISSUE THREAD

**Issue by asciini** [gnome-pomodoro/gnome-pomodoro#717]
The tray icon is not shown under Gnome 46. I searched for a fix and stumbled upon this [forum entry](https://askubuntu.com/questions/1345223/icon-of-gnome-pomodoro-does-not-show-up-how-do-i-fix-it/1494617) which suggests activating the GNOME extension for Pomodoro, but this doesn't work on my GNOME 46 Desktop (see screenshots below). 

I installed the app on NixOS through the [Nix package](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name/gn/gnome-pomodoro)

![image](https://github.com/user-attachments/assets/d97c438e-cff1-4f86-bfe1-299c7bb4d908)
![image](https://github.com/user-attachments/assets/57441f6c-c2c2-4228-a7e8-2c9f2b6f0cc9)

**Comment by kamilprusko** [comment]
Hi!

I'm not the maintainer of the package, but I see that the package is updated to most recent [0.26.0 version](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.26.0) which supports GNOME Shell 46 and 47. I suspect you'll get it once it passes the testing phase. After the package is updated you'll need to log out - GNOME Shell needs to reload the extension.

**Comment by asciini** [comment]
Hi Kamil,

thanks for your help. I was able to solve the problem by sourcing the package from the nix "unstable" channel instead of the main channel, which is more conservative when it comes to updates and thus didn't bring the latest version.
