### ISSUE TITLE
The Timer should automatically stop when the Device is suspended 

### ISSUE THREAD

**Issue by tanaybhomia** [gnome-pomodoro/gnome-pomodoro#718]
## Is your proposal related to a problem?

I usually close the lid of the laptop a lot of times without keeping in mind that the timer is running and when I turn my laptop back on the timer has now logged around 9 hours of me working.

## Describe the solution you'd like

The timer should just automtically just stop running when the laptop is suspended or when the device is locked and then should resume with a notification when it is turned back on

## Describe alternatives you've considered

I have tried creating custom actions provided in the app but couldnt achieve this result 
![image](https://github.com/user-attachments/assets/3d968f63-3e0a-40bc-941d-f5f47920192f)
if I can achieve my feature with this I would love some help to do so.

## Other information

(Write your answer here.)

**Comment by kamilprusko** [comment]
Hi @tanaybhomia 

It's already [implemented](https://github.com/gnome-pomodoro/gnome-pomodoro/blob/wip/gtk4/src/integrations/freedesktop/sleep-monitor-provider.vala) in wip/gtk4 branch. The detection is based on systemd / logind, not sure if it works on systems without it. One thing to improve is preventing autosuspend while the timer is running.

If you want to review it, there's a demo in https://github.com/gnome-pomodoro/gnome-pomodoro/discussions/714 . Keep in mind, there is no GNOME Shell extension nor stats yet.

**Comment by tanaybhomia** [comment]
Thank you I will be trying this build or branch and will provide the insight
