### ISSUE TITLE
Fedora 41 not supported

### ISSUE THREAD

**Issue by lamyergeier** [gnome-pomodoro/gnome-pomodoro#719]
## Issue Summary

From the website:

![image](https://github.com/user-attachments/assets/6854ba59-9563-4a51-b095-e296674489c4)

Why was distribution through <https://extensions.gnome.org/extension/53/pomodoro/> stopped?

![image](https://github.com/user-attachments/assets/e617227e-7e8f-4913-ada3-5d620e38bdec)

**Comment by kamilprusko** [comment]
I've updated the website.

As to why the extension got bundled with the app. I took inspiration from `gnome-shell-extensions` and it simplified distribution - it made sense at the time. I plan to distribute the app through Flathub and the extension again through the official extensions website. I hope it will be ready for GNOME 48.

**Comment by lamyergeier** [comment]
```
$ sudo dnf install gnome-pomodoro
Place your right ring finger on the fingerprint reader
Updating and loading repositories:
Repositories loaded.
Package "gnome-pomodoro-1:0.25.1-2.fc41.x86_64" is already installed.

Nothing to do.
```

**Comment by kchousos** [comment]
Any updates? The build in the fedora repo has a "failed" status.

**Comment by szpak** [comment]
It seems that someone made a koji build of 0.26.0 - https://koji.fedoraproject.org/koji/taskinfo?taskID=125983610, so @kchousos you might use this RPM (or built it locally, as 0.26.0 works perfectly fine with my Fedora 41 with Gnome Shell).

**Comment by lorebored** [comment]
When will the 0.26 version be pushed?

**Comment by szpak** [comment]
I would expect ~4 days looking at:
https://bodhi.fedoraproject.org/updates/FEDORA-2024-24a1f662f9

**Comment by SamuelBorn** [comment]
I updated today to gnome-pomodoro-0.26.
Issue can be closed now.

**Comment by lamyergeier** [comment]
@kamilprusko 

Still facing problem in Fedora 42


```
$ sudo dnf install gnome-pomodoro
Place your right ring finger on the fingerprint reader
Updating and loading repositories:
Repositories loaded.
Package "gnome-pomodoro-1:0.26.0-2.fc42.x86_64" is already installed.

Nothing to do.
```
