### ISSUE TITLE
After update to Gnome 47 icon disappeared from system tray.

### ISSUE THREAD

**Issue by bigkrp** [gnome-pomodoro/gnome-pomodoro#722]
## Issue Summary
This extension worked as expected on the previous version of Fedora with gnome 40.

## Steps to Reproduce

1. Install gnome pomodoro on latest Fedora 41

## Expected Behavior
The system tray icon exists with all the functionality

## Current Behavior
No system tray icon for gnome-pomodoro

**Comment by kamilprusko** [comment]
Hi @bigkrp 

The package for Fedora 41 do not ship latest release 0.26.0. The update awaits for approval https://src.fedoraproject.org/rpms/gnome-pomodoro/pull-request/6 . Unfortunately, i'm not the maintainer of Fedora package, there's little i can do. 

Closing duplicate. Follow #719
